Snapshot-Content-Location: https://codex.steam-labz.com
Subject: Create Next App
Date: Thu, 17 Apr 2025 14:30:31 -0500
MIME-Version: 1.0
Content-Type: multipart/related;
	type="text/html";
	boundary="----MultipartBoundary--0qBUgy5tPqKL35ZdjCbOOhQnRB2eG5WhwTDH1o7iZA----"


------MultipartBoundary--0qBUgy5tPqKL35ZdjCbOOhQnRB2eG5WhwTDH1o7iZA----
Content-Type: text/html
Content-ID: <frame-4C9CCA9BA194A1D14B4555976656F6CC@mhtml.blink>
Content-Transfer-Encoding: binary
Content-Location: https://codex.steam-labz.com

<!DOCTYPE html><html lang="en" class="dark"><head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1"><link rel="preload" href="https://pflimypj.manus.space/_next/static/media/569ce4b8f30dc480-s.p.woff2" as="font" crossorigin="" type="font/woff2"><link rel="preload" href="https://pflimypj.manus.space/_next/static/media/93f479601ee12b01-s.p.woff2" as="font" crossorigin="" type="font/woff2"><link rel="stylesheet" href="https://pflimypj.manus.space/_next/static/css/3f0efcce4dc0fac6.css" data-precedence="next"><link rel="preload" as="script" fetchpriority="low" href="https://pflimypj.manus.space/_next/static/chunks/webpack-9aa2fa78335f4e6b.js"><meta name="next-size-adjust" content=""><title>Create Next App</title><meta name="description" content="Generated by create next app"><link rel="icon" href="https://pflimypj.manus.space/favicon.ico" type="image/x-icon" sizes="16x16"></head><body class="__variable_4d318d __variable_ea5f4b antialiased"><main class="flex min-h-screen flex-col"><header class="bg-[#1a5b8e] p-4 text-white"><div class="container mx-auto flex items-center justify-between"><div class="flex items-center gap-2"><div class="w-8 h-8 relative"><div class="w-8 h-8 bg-[#2e7d32] rounded-full flex items-center justify-center"><span class="text-white font-bold">SL</span></div></div><h1 class="text-2xl font-bold">STEAM-Labz Codex Terminal</h1></div><nav><ul class="flex gap-4"><li><a href="https://steam-labz.com/codex" target="_blank" rel="noopener noreferrer" class="hover:underline">Documentation</a></li><li><a href="https://github.com/openai/codex" target="_blank" rel="noopener noreferrer" class="hover:underline">GitHub</a></li></ul></nav></div></header><div class="flex flex-1 flex-col md:flex-row"><aside class="bg-[#121212] p-4 text-white md:w-64"><h2 class="mb-4 text-xl font-bold">Settings</h2><div class="mb-4"><label for="api-key" class="mb-1 block text-sm">OpenAI API Key</label><input type="password" id="api-key" class="w-full rounded bg-gray-800 p-2 text-white" placeholder="sk-..." value=""></div><div class="mb-4"><label class="mb-1 block text-sm">Approval Mode</label><select class="w-full rounded bg-gray-800 p-2 text-white"><option value="suggest" selected="">Suggest (Default)</option><option value="auto-edit">Auto Edit</option><option value="full-auto">Full Auto</option></select></div><div class="mb-4"><button class="w-full rounded bg-[#ff6b35] p-2 text-white hover:bg-opacity-90">Apply Settings</button></div><div class="mt-8 h-[calc(100vh-24rem)]"><h3 class="mb-2 text-lg font-bold">Files</h3><div class="overflow-auto max-h-full"><ul class="space-y-1"><li class="p-2 hover:bg-gray-800 cursor-pointer rounded ">📁 <!-- -->Documents</li><li class="p-2 hover:bg-gray-800 cursor-pointer rounded ">📁 <!-- -->Projects</li><li class="p-2 hover:bg-gray-800 cursor-pointer rounded bg-gray-700">📄 <!-- -->README.md</li><li class="p-2 hover:bg-gray-800 cursor-pointer rounded ">📄 <!-- -->example.js</li></ul></div></div></aside><div class="flex-1 bg-[#121212] p-4"><div class="h-[calc(100vh-8rem)] rounded border border-gray-700 flex flex-col"><div class="flex-1 bg-black text-white font-mono p-4 overflow-auto" style="white-space:pre-wrap"><div>Welcome to STEAM-Labz Codex Terminal</div><div>Type "help" for available commands</div><div></div><div>Selected file: README.md</div><div></div><div>Selected file: README.md</div><div></div></div><div class="flex items-center bg-gray-900 p-2"><span class="text-[#ff6b35] mr-2">$</span><input type="text" class="flex-1 bg-transparent text-white outline-none font-mono" placeholder="Type a command..." autofocus="" value=""></div></div></div></div><footer class="bg-[#121212] border-t border-gray-800 p-2 text-center text-gray-400 text-sm"><p>STEAM-Labz Codex Terminal © <!-- -->2025<!-- --> | <a href="https://steam-labz.com/" class="text-[#ff6b35] hover:underline">steam-labz.com</a></p></footer></main><footer-btn><template shadowmode="open"><div class="wrapper">
                <div class="page-footer">
                    <div class="tooltip-dialog">content may contain inaccuracies; double-check before use. Do not submit passwords, credit cards, or personal information.</div>
                    <div class="footer-close-btn">
                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 16 16" fill="none">
                        <g clip-path="url(#clip0_5850_97234)">
                        <path fill-rule="evenodd" clip-rule="evenodd" d="M0.733398 8.00104C0.733398 3.98777 3.9868 0.734375 8.00006 0.734375C12.0133 0.734375 15.2667 3.98777 15.2667 8.00104C15.2667 12.0143 12.0133 15.2677 8.00006 15.2677C3.9868 15.2677 0.733398 12.0143 0.733398 8.00104Z" fill="white"></path>
                        <path d="M1.2334 8.00104C1.2334 4.26391 4.26294 1.23438 8.00006 1.23438C11.7372 1.23438 14.7667 4.26391 14.7667 8.00104C14.7667 11.7382 11.7372 14.7677 8.00006 14.7677C4.26294 14.7677 1.2334 11.7382 1.2334 8.00104Z" stroke="black" stroke-opacity="0.14" stroke-linecap="round" stroke-linejoin="round"></path>
                        <path fill-rule="evenodd" clip-rule="evenodd" d="M5.57576 5.57613C5.81007 5.34181 6.18997 5.34181 6.42429 5.57613L8.00002 7.15186L9.57576 5.57613C9.81007 5.34181 10.19 5.34181 10.4243 5.57613C10.6586 5.81044 10.6586 6.19034 10.4243 6.42465L8.84855 8.00039L10.4243 9.57613C10.6586 9.81044 10.6586 10.1903 10.4243 10.4247C10.19 10.659 9.81007 10.659 9.57576 10.4247L8.00002 8.84892L6.42429 10.4247C6.18997 10.659 5.81007 10.659 5.57576 10.4247C5.34145 10.1903 5.34145 9.81044 5.57576 9.57613L7.1515 8.00039L5.57576 6.42465C5.34145 6.19034 5.34145 5.81044 5.57576 5.57613Z" fill="#858481"></path>
                        </g>
                        <defs>
                        <clipPath id="clip0_5850_97234">
                        <rect width="16" height="16" fill="white"></rect>
                        </clipPath>
                        </defs>
                        </svg>
                    </div>
                    <div class="footer-bg">
                        <div class="tooltip-box">
                            <div class="tooltip-desc">This website is under development. Use Caution!</div>
                            <span class="tooltip-icon">
                                <svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" viewBox="0 0 12 12" fill="none">
                                    <g clip-path="url(#clip0_4345_83044)">
                                        <path d="M6 8V6M6 4H6.005M11 6C11 8.76142 8.76142 11 6 11C3.23858 11 1 8.76142 1 6C1 3.23858 3.23858 1 6 1C8.76142 1 11 3.23858 11 6Z" stroke="#858481" stroke-linecap="round" stroke-linejoin="round"></path>
                                    </g>
                                    <defs>
                                        <clipPath id="clip0_4345_83044">
                                            <rect width="12" height="12" fill="white"></rect>
                                        </clipPath>
                                    </defs>
                                </svg>
                            </span>
                        </div>
                    </div>
                    <a href="https://steam-labz.com" target="_blank" class="footer-button">
                        <span class="footer-logo">
                            <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 18 18" fill="none">
                                <path d="M13.2251 16.9379C14.4717 16.147 15.3336 11.9052 15.144 10.6421C15.144 10.6421 14.9464 9.96396 14.4643 9.96394C13.9821 9.96391 13.7815 10.4719 13.7815 10.4719C13.7815 10.4719 13.6546 10.9409 13.4555 11.5313C13.1474 12.4447 13.0178 13.5718 12.2143 13.8571C11.4107 14.1425 10.6071 13.8725 10.6071 13.8725C11.1535 15.9448 11.9785 17.7288 13.2251 16.9379Z" fill="white"></path>
                                <path fill-rule="evenodd" clip-rule="evenodd" d="M7.04826 9.17689C6.59029 9.22824 6.34906 9.40136 6.26768 9.48274C5.94625 9.80417 5.78554 10.1256 5.78554 10.2863C5.78554 10.447 5.40745 9.53393 5.32437 9.44837C5.07703 9.19366 5.083 8.78667 5.33771 8.53933C5.69527 8.19212 6.28003 7.96925 6.90502 7.89918C7.55323 7.82651 8.3219 7.9075 9.09971 8.25205C10.0075 8.65415 10.4937 9.50199 10.6773 10.2768C10.7705 10.6701 10.7943 11.0743 10.7466 11.4426C10.7002 11.8002 10.5781 12.1826 10.3242 12.4736C9.79525 13.0799 9.01508 13.0116 8.593 12.9221C8.35518 12.8716 8.14542 12.7975 7.99786 12.738C7.92303 12.7079 7.86158 12.6804 7.81747 12.6597C7.79535 12.6493 7.77743 12.6406 7.7642 12.6341C7.75757 12.6308 7.75211 12.628 7.74786 12.6259L7.7424 12.6231L7.74037 12.622L7.73915 12.6214C7.73915 12.6214 7.7388 12.6212 8.03568 12.051L7.7388 12.6212C7.42389 12.4573 7.30152 12.069 7.46548 11.7541C7.62912 11.4398 8.01612 11.3173 8.3307 11.4798M8.3307 11.4798L8.33145 11.4802L8.3307 11.4798ZM8.3307 11.4798L8.33531 11.4822C8.34052 11.4847 8.3498 11.4893 8.36271 11.4953C8.38864 11.5075 8.42852 11.5254 8.4788 11.5457C8.58146 11.5871 8.71705 11.6341 8.85982 11.6644C9.19892 11.7363 9.32081 11.668 9.3554 11.6284C9.38325 11.5965 9.44396 11.4899 9.47154 11.2773C9.49771 11.0755 9.48663 10.8281 9.42625 10.5733C9.30267 10.0519 9.00685 9.61712 8.57899 9.42759C8.02117 9.1805 7.48301 9.12815 7.04826 9.17689" fill="white"></path>
                                <path fill-rule="evenodd" clip-rule="evenodd" d="M2.79812 2.53348C2.64176 2.85224 2.7734 3.2374 3.09216 3.39376C3.55 3.61834 3.94731 3.83979 4.34068 4.28331C4.57627 4.54892 4.98258 4.57326 5.2482 4.33767C5.51381 4.10208 5.53815 3.69577 5.30256 3.43016C4.742 2.79815 4.16499 2.48794 3.65839 2.23944C3.33963 2.08308 2.95448 2.21473 2.79812 2.53348Z" fill="white"></path>
                                <path fill-rule="evenodd" clip-rule="evenodd" d="M6.27275 0.662519C5.92831 0.748629 5.71889 1.09766 5.805 1.4421C5.86516 1.68274 5.92127 1.8885 5.97263 2.07686C6.07093 2.43738 6.15185 2.73415 6.21054 3.08969C6.26837 3.43999 6.59923 3.67708 6.94952 3.61926C7.29982 3.56143 7.53692 3.23058 7.47909 2.88028C7.40972 2.46006 7.3017 2.06246 7.19328 1.66338C7.14526 1.48666 7.09717 1.30966 7.05233 1.13027C6.96622 0.785827 6.61719 0.57641 6.27275 0.662519Z" fill="white"></path>
                                <path d="M8.99979 3.21456C9.16051 2.57171 9.32122 2.08956 9.61377 1.60742" stroke="white" stroke-width="1.28571" stroke-miterlimit="10" stroke-linecap="round"></path>
                                <path fill-rule="evenodd" clip-rule="evenodd" d="M11.3613 6.26832C12.6366 6.52316 12.6368 6.52221 12.6368 6.52221L12.637 6.52126L12.6373 6.51931L12.6381 6.51527L12.6396 6.50658C12.6407 6.50054 12.6418 6.49395 12.6429 6.48687C12.6452 6.47271 12.6476 6.45641 12.65 6.43816C12.6548 6.40191 12.6596 6.35662 12.6628 6.30419C12.6689 6.20315 12.6702 6.05635 12.6443 5.88608C12.5954 5.56354 12.4075 4.95215 11.7455 4.59774L11.6146 4.52762L11.4715 4.48801L11.1424 5.7144C11.4358 5.8715 11.3613 6.26832 11.3613 6.26832ZM11.1573 7.07742L11.3613 6.26832L12.6366 6.52316L12.6296 6.56049L12.4237 7.37732C12.3841 7.57807 12.3789 7.69285 12.381 7.75349C12.3828 7.80284 12.3892 7.81904 12.3924 7.82698L12.3927 7.8279C12.4008 7.84841 12.4216 7.89289 12.4977 8.00832C12.5287 8.05537 12.561 8.10252 12.6021 8.1626C12.613 8.1785 12.6245 8.19531 12.6367 8.21327C12.6919 8.29416 12.7565 8.38953 12.825 8.49621C13.2527 9.16281 13.2947 9.80259 13.2925 10.2126C13.2924 10.2186 13.2924 10.2246 13.2923 10.2305C13.3435 10.2481 13.3978 10.2658 13.4555 10.2841C13.4745 10.2902 13.4997 10.2982 13.5262 10.3065C13.5634 10.3183 13.6031 10.3308 13.6314 10.3399C13.6872 10.3577 13.7584 10.381 13.8272 10.4067C13.8751 10.4245 13.9211 10.4423 13.9644 10.4603C14.0059 10.4775 14.0566 10.4995 14.1099 10.5264C14.1513 10.5473 14.2186 10.5831 14.2948 10.6359L14.9647 10.9242L14.955 11.7823C14.9493 12.2868 14.7463 12.8187 14.6023 13.148C14.4436 13.5111 14.2339 13.8983 14.0408 14.1556C13.7712 14.515 13.4657 14.8945 13.0981 15.1372C12.8815 15.2802 12.6198 15.394 12.3111 15.4313C12.0361 15.4645 11.7981 15.4277 11.6232 15.3851L11.5717 15.3745C11.5199 15.3639 11.4456 15.3486 11.3553 15.3298C11.1748 15.2922 10.9287 15.2404 10.6678 15.1837C10.1867 15.0793 9.53471 14.9331 9.22715 14.8311L9.20492 14.8237L9.18296 14.8155C9.04655 14.7649 8.81591 14.7081 8.43387 14.621C8.41077 14.6157 8.38722 14.6103 8.36328 14.6049C8.03371 14.5299 7.6281 14.4376 7.24401 14.3212C6.8462 14.2008 6.35418 14.0216 5.9364 13.7296C5.4979 13.4232 4.99936 12.8829 4.9716 12.0723C4.96744 11.951 4.97023 11.8337 4.97774 11.7224C4.78027 11.5084 4.61454 11.2286 4.53078 10.8703C4.44918 10.5212 4.49431 10.2118 4.55156 9.99459C4.60897 9.7768 4.69617 9.58643 4.76904 9.44413C4.79364 9.3961 4.81915 9.34874 4.8446 9.30298C4.60356 9.22692 4.3313 9.13294 4.06631 9.01999C3.72023 8.87246 3.22918 8.62908 2.86258 8.2362C2.66514 8.0246 2.4584 7.72132 2.37481 7.3248C2.28733 6.90985 2.36002 6.51171 2.53036 6.1708C2.94502 5.34093 3.73706 5.04773 4.44152 5.02237C5.07762 4.99946 5.75449 5.17745 6.36097 5.39016C6.91355 5.58397 7.70443 5.94444 8.3763 6.25842C8.5976 5.89554 8.88932 5.48549 9.16548 5.15432L9.22034 5.08854L9.28382 5.03075C9.75896 4.59828 10.2927 4.45288 10.6994 4.42169C10.8988 4.4064 11.0705 4.41781 11.1989 4.43448C11.2638 4.44291 11.3198 4.45295 11.3652 4.46245C11.388 4.46721 11.4083 4.47188 11.426 4.4762C11.4349 4.47837 11.4431 4.48045 11.4507 4.48243L11.4616 4.48531L11.4666 4.48668L11.4691 4.48735L11.4703 4.48768C11.4703 4.48768 11.4715 4.48801 11.1424 5.7144C11.1424 5.7144 10.6292 5.57232 10.188 5.96175C10.1836 5.96567 10.1792 5.96965 10.1747 5.97368C10.161 5.99009 10.1473 6.0067 10.1336 6.02351C10.1139 6.04768 10.0941 6.07224 10.0743 6.09711C10.0685 6.10441 10.0627 6.11174 10.0569 6.1191C9.61666 6.67768 9.64277 6.91103 8.83914 7.87543C8.83914 7.87543 8.4205 7.68157 8.1701 7.56386C7.9983 7.48311 7.81669 7.39774 7.63164 7.31169C7.03464 7.03411 6.40173 6.74946 5.94628 6.58972C4.82494 6.19643 3.99821 6.14651 3.69645 6.75042C3.29839 7.54707 4.9148 8.00866 5.72705 8.24061C5.8981 8.28945 6.03349 8.32811 6.10689 8.35758C6.52348 8.52479 6.55255 8.86031 6.42848 9.16103C6.35609 9.33651 6.31482 9.43541 6.10706 9.64317C5.78563 9.9646 5.73292 10.3452 5.7943 10.6078C5.82503 10.7392 5.88582 10.8348 5.95809 10.9044C6.15197 11.0909 6.42842 11.0897 6.42842 11.0897C6.42842 11.0897 6.25016 11.5453 6.26759 12.0541C6.27143 12.1661 6.30155 12.268 6.35346 12.3612C6.66163 12.9145 7.73774 13.1596 8.64189 13.3655C9.02162 13.452 9.37102 13.5316 9.62046 13.6242C10.0676 13.7726 11.8925 14.1433 11.8925 14.1433C12.2292 14.2317 12.438 14.1247 12.9919 13.3864C13.2219 13.0797 13.653 12.2123 13.6583 11.7435C13.5884 11.7134 13.5835 11.7029 13.5786 11.6924C13.5718 11.6779 13.565 11.6633 13.3882 11.5974C13.329 11.5754 13.2499 11.5504 13.1593 11.5218C12.7822 11.4029 12.2071 11.2215 12.0534 10.929C11.9788 10.787 11.9846 10.5964 11.9915 10.3736C12.0022 10.0271 12.0153 9.60261 11.732 9.16115C11.6624 9.05276 11.5957 8.95523 11.5333 8.864C11.1781 8.34469 10.9626 8.0296 11.1573 7.07742ZM5.21736 8.64574C5.21818 8.64341 5.21787 8.64394 5.21684 8.64717L5.21736 8.64574ZM13.2859 10.6214C13.2859 10.6214 13.2859 10.6164 13.2849 10.6077C13.2852 10.6173 13.2859 10.6214 13.2859 10.6214Z" fill="white"></path>
                            </svg>
                        </span>
                        <div class="title">STEAM Powered</div>
                        <div class="create-title">by STEAM-Labz</div>
                    </a>
                </div>

                <div class="page-footer-mobile">
                    <div class="footer-button">
                        <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 18 18" fill="none">
                            <path d="M13.2251 16.9379C14.4717 16.147 15.3336 11.9052 15.144 10.6421C15.144 10.6421 14.9464 9.96396 14.4643 9.96394C13.9821 9.96391 13.7815 10.4719 13.7815 10.4719C13.7815 10.4719 13.6546 10.9409 13.4555 11.5313C13.1474 12.4447 13.0178 13.5718 12.2143 13.8571C11.4107 14.1425 10.6071 13.8725 10.6071 13.8725C11.1535 15.9448 11.9785 17.7288 13.2251 16.9379Z" fill="white"></path>
                            <path fill-rule="evenodd" clip-rule="evenodd" d="M7.04826 9.17689C6.59029 9.22824 6.34906 9.40136 6.26768 9.48274C5.94625 9.80417 5.78554 10.1256 5.78554 10.2863C5.78554 10.447 5.40745 9.53393 5.32437 9.44837C5.07703 9.19366 5.083 8.78667 5.33771 8.53933C5.69527 8.19212 6.28003 7.96925 6.90502 7.89918C7.55323 7.82651 8.3219 7.9075 9.09971 8.25205C10.0075 8.65415 10.4937 9.50199 10.6773 10.2768C10.7705 10.6701 10.7943 11.0743 10.7466 11.4426C10.7002 11.8002 10.5781 12.1826 10.3242 12.4736C9.79525 13.0799 9.01508 13.0116 8.593 12.9221C8.35518 12.8716 8.14542 12.7975 7.99786 12.738C7.92303 12.7079 7.86158 12.6804 7.81747 12.6597C7.79535 12.6493 7.77743 12.6406 7.7642 12.6341C7.75757 12.6308 7.75211 12.628 7.74786 12.6259L7.7424 12.6231L7.74037 12.622L7.73915 12.6214C7.73915 12.6214 7.7388 12.6212 8.03568 12.051L7.7388 12.6212C7.42389 12.4573 7.30152 12.069 7.46548 11.7541C7.62912 11.4398 8.01612 11.3173 8.3307 11.4798M8.3307 11.4798L8.33145 11.4802L8.3307 11.4798ZM8.3307 11.4798L8.33531 11.4822C8.34052 11.4847 8.3498 11.4893 8.36271 11.4953C8.38864 11.5075 8.42852 11.5254 8.4788 11.5457C8.58146 11.5871 8.71705 11.6341 8.85982 11.6644C9.19892 11.7363 9.32081 11.668 9.3554 11.6284C9.38325 11.5965 9.44396 11.4899 9.47154 11.2773C9.49771 11.0755 9.48663 10.8281 9.42625 10.5733C9.30267 10.0519 9.00685 9.61712 8.57899 9.42759C8.02117 9.1805 7.48301 9.12815 7.04826 9.17689" fill="white"></path>
                            <path fill-rule="evenodd" clip-rule="evenodd" d="M2.79812 2.53348C2.64176 2.85224 2.7734 3.2374 3.09216 3.39376C3.55 3.61834 3.94731 3.83979 4.34068 4.28331C4.57627 4.54892 4.98258 4.57326 5.2482 4.33767C5.51381 4.10208 5.53815 3.69577 5.30256 3.43016C4.742 2.79815 4.16499 2.48794 3.65839 2.23944C3.33963 2.08308 2.95448 2.21473 2.79812 2.53348Z" fill="white"></path>
                            <path fill-rule="evenodd" clip-rule="evenodd" d="M6.27275 0.662519C5.92831 0.748629 5.71889 1.09766 5.805 1.4421C5.86516 1.68274 5.92127 1.8885 5.97263 2.07686C6.07093 2.43738 6.15185 2.73415 6.21054 3.08969C6.26837 3.43999 6.59923 3.67708 6.94952 3.61926C7.29982 3.56143 7.53692 3.23058 7.47909 2.88028C7.40972 2.46006 7.3017 2.06246 7.19328 1.66338C7.14526 1.48666 7.09717 1.30966 7.05233 1.13027C6.96622 0.785827 6.61719 0.57641 6.27275 0.662519Z" fill="white"></path>
                            <path d="M8.99979 3.21456C9.16051 2.57171 9.32122 2.08956 9.61377 1.60742" stroke="white" stroke-width="1.28571" stroke-miterlimit="10" stroke-linecap="round"></path>
                            <path fill-rule="evenodd" clip-rule="evenodd" d="M11.3613 6.26832C12.6366 6.52316 12.6368 6.52221 12.6368 6.52221L12.637 6.52126L12.6373 6.51931L12.6381 6.51527L12.6396 6.50658C12.6407 6.50054 12.6418 6.49395 12.6429 6.48687C12.6452 6.47271 12.6476 6.45641 12.65 6.43816C12.6548 6.40191 12.6596 6.35662 12.6628 6.30419C12.6689 6.20315 12.6702 6.05635 12.6443 5.88608C12.5954 5.56354 12.4075 4.95215 11.7455 4.59774L11.6146 4.52762L11.4715 4.48801L11.1424 5.7144C11.4358 5.8715 11.3613 6.26832 11.3613 6.26832ZM11.1573 7.07742L11.3613 6.26832L12.6366 6.52316L12.6296 6.56049L12.4237 7.37732C12.3841 7.57807 12.3789 7.69285 12.381 7.75349C12.3828 7.80284 12.3892 7.81904 12.3924 7.82698L12.3927 7.8279C12.4008 7.84841 12.4216 7.89289 12.4977 8.00832C12.5287 8.05537 12.561 8.10252 12.6021 8.1626C12.613 8.1785 12.6245 8.19531 12.6367 8.21327C12.6919 8.29416 12.7565 8.38953 12.825 8.49621C13.2527 9.16281 13.2947 9.80259 13.2925 10.2126C13.2924 10.2186 13.2924 10.2246 13.2923 10.2305C13.3435 10.2481 13.3978 10.2658 13.4555 10.2841C13.4745 10.2902 13.4997 10.2982 13.5262 10.3065C13.5634 10.3183 13.6031 10.3308 13.6314 10.3399C13.6872 10.3577 13.7584 10.381 13.8272 10.4067C13.8751 10.4245 13.9211 10.4423 13.9644 10.4603C14.0059 10.4775 14.0566 10.4995 14.1099 10.5264C14.1513 10.5473 14.2186 10.5831 14.2948 10.6359L14.9647 10.9242L14.955 11.7823C14.9493 12.2868 14.7463 12.8187 14.6023 13.148C14.4436 13.5111 14.2339 13.8983 14.0408 14.1556C13.7712 14.515 13.4657 14.8945 13.0981 15.1372C12.8815 15.2802 12.6198 15.394 12.3111 15.4313C12.0361 15.4645 11.7981 15.4277 11.6232 15.3851L11.5717 15.3745C11.5199 15.3639 11.4456 15.3486 11.3553 15.3298C11.1748 15.2922 10.9287 15.2404 10.6678 15.1837C10.1867 15.0793 9.53471 14.9331 9.22715 14.8311L9.20492 14.8237L9.18296 14.8155C9.04655 14.7649 8.81591 14.7081 8.43387 14.621C8.41077 14.6157 8.38722 14.6103 8.36328 14.6049C8.03371 14.5299 7.6281 14.4376 7.24401 14.3212C6.8462 14.2008 6.35418 14.0216 5.9364 13.7296C5.4979 13.4232 4.99936 12.8829 4.9716 12.0723C4.96744 11.951 4.97023 11.8337 4.97774 11.7224C4.78027 11.5084 4.61454 11.2286 4.53078 10.8703C4.44918 10.5212 4.49431 10.2118 4.55156 9.99459C4.60897 9.7768 4.69617 9.58643 4.76904 9.44413C4.79364 9.3961 4.81915 9.34874 4.8446 9.30298C4.60356 9.22692 4.3313 9.13294 4.06631 9.01999C3.72023 8.87246 3.22918 8.62908 2.86258 8.2362C2.66514 8.0246 2.4584 7.72132 2.37481 7.3248C2.28733 6.90985 2.36002 6.51171 2.53036 6.1708C2.94502 5.34093 3.73706 5.04773 4.44152 5.02237C5.07762 4.99946 5.75449 5.17745 6.36097 5.39016C6.91355 5.58397 7.70443 5.94444 8.3763 6.25842C8.5976 5.89554 8.88932 5.48549 9.16548 5.15432L9.22034 5.08854L9.28382 5.03075C9.75896 4.59828 10.2927 4.45288 10.6994 4.42169C10.8988 4.4064 11.0705 4.41781 11.1989 4.43448C11.2638 4.44291 11.3198 4.45295 11.3652 4.46245C11.388 4.46721 11.4083 4.47188 11.426 4.4762C11.4349 4.47837 11.4431 4.48045 11.4507 4.48243L11.4616 4.48531L11.4666 4.48668L11.4691 4.48735L11.4703 4.48768C11.4703 4.48768 11.4715 4.48801 11.1424 5.7144C11.1424 5.7144 10.6292 5.57232 10.188 5.96175C10.1836 5.96567 10.1792 5.96965 10.1747 5.97368C10.161 5.99009 10.1473 6.0067 10.1336 6.02351C10.1139 6.04768 10.0941 6.07224 10.0743 6.09711C10.0685 6.10441 10.0627 6.11174 10.0569 6.1191C9.61666 6.67768 9.64277 6.91103 8.83914 7.87543C8.83914 7.87543 8.4205 7.68157 8.1701 7.56386C7.9983 7.48311 7.81669 7.39774 7.63164 7.31169C7.03464 7.03411 6.40173 6.74946 5.94628 6.58972C4.82494 6.19643 3.99821 6.14651 3.69645 6.75042C3.29839 7.54707 4.9148 8.00866 5.72705 8.24061C5.8981 8.28945 6.03349 8.32811 6.10689 8.35758C6.52348 8.52479 6.55255 8.86031 6.42848 9.16103C6.35609 9.33651 6.31482 9.43541 6.10706 9.64317C5.78563 9.9646 5.73292 10.3452 5.7943 10.6078C5.82503 10.7392 5.88582 10.8348 5.95809 10.9044C6.15197 11.0909 6.42842 11.0897 6.42842 11.0897C6.42842 11.0897 6.25016 11.5453 6.26759 12.0541C6.27143 12.1661 6.30155 12.268 6.35346 12.3612C6.66163 12.9145 7.73774 13.1596 8.64189 13.3655C9.02162 13.452 9.37102 13.5316 9.62046 13.6242C10.0676 13.7726 11.8925 14.1433 11.8925 14.1433C12.2292 14.2317 12.438 14.1247 12.9919 13.3864C13.2219 13.0797 13.653 12.2123 13.6583 11.7435C13.5884 11.7134 13.5835 11.7029 13.5786 11.6924C13.5718 11.6779 13.565 11.6633 13.3882 11.5974C13.329 11.5754 13.2499 11.5504 13.1593 11.5218C12.7822 11.4029 12.2071 11.2215 12.0534 10.929C11.9788 10.787 11.9846 10.5964 11.9915 10.3736C12.0022 10.0271 12.0153 9.60261 11.732 9.16115C11.6624 9.05276 11.5957 8.95523 11.5333 8.864C11.1781 8.34469 10.9626 8.0296 11.1573 7.07742ZM5.21736 8.64574C5.21818 8.64341 5.21787 8.64394 5.21684 8.64717L5.21736 8.64574ZM13.2859 10.6214C13.2859 10.6214 13.2859 10.6164 13.2849 10.6077C13.2852 10.6173 13.2859 10.6214 13.2859 10.6214Z" fill="white"></path>
                        </svg>
                        <div class="title">STEAM Powered</div>
                        <div class="create-title">by STEAM-Labz</div>
                    </div>
                    <div class="footer-dialog">
                        <div class="dialog-box">
                            <div class="dialog-header">
                                <div class="dialog-header-title">Made by STEAM-Labz</div>
                                <span class="dialog-header-icon">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 18 18" fill="none">
                                        <path fill-rule="evenodd" clip-rule="evenodd" d="M3.2729 3.27192C3.5365 3.00832 3.96389 3.00832 4.22749 3.27192L9.0002 8.04462L13.7729 3.27192C14.0365 3.00832 14.4639 3.00832 14.7275 3.27192C14.9911 3.53553 14.9911 3.96291 14.7275 4.22652L9.95479 8.99922L14.7275 13.7719C14.9911 14.0355 14.9911 14.4629 14.7275 14.7265C14.4639 14.9901 14.0365 14.9901 13.7729 14.7265L9.0002 9.95381L4.22749 14.7265C3.96389 14.9901 3.5365 14.9901 3.2729 14.7265C3.00929 14.4629 3.00929 14.0355 3.2729 13.7719L8.0456 8.99922L3.2729 4.22652C3.00929 3.96291 3.00929 3.53553 3.2729 3.27192Z" fill="#858481"></path>
                                    </svg>
                                </span>
                            </div>
                            <div class="dialog-body">
                                <div>This website was created with STEAM. Use with caution.</div>
                                <div>
                                    Content may contain inaccuracies; double-check before use. Do not submit
                                    passwords, credit cards, or personal information.
                                </div>
                            </div>
                            <div class="dialog-footer">
                                <div class="dialog-footer-button-left">Cancel</div>
                                <div class="dialog-footer-button-right">Delete this btn [98]</div>
                            </div>
                        </div>
                    </div>
                </div>
            </div></template></footer-btn>


		<next-route-announcer style="position: absolute;"><template shadowmode="open"><div aria-live="assertive" id="__next-route-announcer__" role="alert" style="position: absolute; border: 0px; height: 1px; margin: -1px; padding: 0px; width: 1px; clip: rect(0px, 0px, 0px, 0px); overflow: hidden; white-space: nowrap; overflow-wrap: normal;"></div></template></next-route-announcer></body></html>
------MultipartBoundary--0qBUgy5tPqKL35ZdjCbOOhQnRB2eG5WhwTDH1o7iZA----
Content-Type: text/css
Content-Transfer-Encoding: binary
Content-Location: https://pflimypj.manus.space/_next/static/css/3f0efcce4dc0fac6.css

@charset "utf-8";

@font-face { font-family: Geist; font-style: normal; font-weight: 100 900; font-display: swap; src: url("/_next/static/media/ba015fad6dcf6784-s.woff2") format("woff2"); unicode-range: U+100-2BA, U+2BD-2C5, U+2C7-2CC, U+2CE-2D7, U+2DD-2FF, U+304, U+308, U+329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF; }

@font-face { font-family: Geist; font-style: normal; font-weight: 100 900; font-display: swap; src: url("/_next/static/media/569ce4b8f30dc480-s.p.woff2") format("woff2"); unicode-range: U+0-FF, U+131, U+152-153, U+2BB-2BC, U+2C6, U+2DA, U+2DC, U+304, U+308, U+329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD; }

@font-face { font-family: "Geist Fallback"; src: local("Arial"); ascent-override: 95.94%; descent-override: 28.16%; line-gap-override: 0%; size-adjust: 104.76%; }

.__className_4d318d { font-family: Geist, "Geist Fallback"; font-style: normal; }

.__variable_4d318d { --font-geist-sans: "Geist","Geist Fallback"; }

@font-face { font-family: "Geist Mono"; font-style: normal; font-weight: 100 900; font-display: swap; src: url("/_next/static/media/747892c23ea88013-s.woff2") format("woff2"); unicode-range: U+100-2BA, U+2BD-2C5, U+2C7-2CC, U+2CE-2D7, U+2DD-2FF, U+304, U+308, U+329, U+1D00-1DBF, U+1E00-1E9F, U+1EF2-1EFF, U+2020, U+20A0-20AB, U+20AD-20C0, U+2113, U+2C60-2C7F, U+A720-A7FF; }

@font-face { font-family: "Geist Mono"; font-style: normal; font-weight: 100 900; font-display: swap; src: url("/_next/static/media/93f479601ee12b01-s.p.woff2") format("woff2"); unicode-range: U+0-FF, U+131, U+152-153, U+2BB-2BC, U+2C6, U+2DA, U+2DC, U+304, U+308, U+329, U+2000-206F, U+20AC, U+2122, U+2191, U+2193, U+2212, U+2215, U+FEFF, U+FFFD; }

@font-face { font-family: "Geist Mono Fallback"; src: local("Arial"); ascent-override: 74.67%; descent-override: 21.92%; line-gap-override: 0%; size-adjust: 134.59%; }

.__className_ea5f4b { font-family: "Geist Mono", "Geist Mono Fallback"; font-style: normal; }

.__variable_ea5f4b { --font-geist-mono: "Geist Mono","Geist Mono Fallback"; }

*, ::after, ::before { --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-pan-x: ; --tw-pan-y: ; --tw-pinch-zoom: ; --tw-scroll-snap-strictness: proximity; --tw-gradient-from-position: ; --tw-gradient-via-position: ; --tw-gradient-to-position: ; --tw-ordinal: ; --tw-slashed-zero: ; --tw-numeric-figure: ; --tw-numeric-spacing: ; --tw-numeric-fraction: ; --tw-ring-inset: ; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; --tw-blur: ; --tw-brightness: ; --tw-contrast: ; --tw-grayscale: ; --tw-hue-rotate: ; --tw-invert: ; --tw-saturate: ; --tw-sepia: ; --tw-drop-shadow: ; --tw-backdrop-blur: ; --tw-backdrop-brightness: ; --tw-backdrop-contrast: ; --tw-backdrop-grayscale: ; --tw-backdrop-hue-rotate: ; --tw-backdrop-invert: ; --tw-backdrop-opacity: ; --tw-backdrop-saturate: ; --tw-backdrop-sepia: ; --tw-contain-size: ; --tw-contain-layout: ; --tw-contain-paint: ; --tw-contain-style: ; }

::backdrop { --tw-border-spacing-x: 0; --tw-border-spacing-y: 0; --tw-translate-x: 0; --tw-translate-y: 0; --tw-rotate: 0; --tw-skew-x: 0; --tw-skew-y: 0; --tw-scale-x: 1; --tw-scale-y: 1; --tw-pan-x: ; --tw-pan-y: ; --tw-pinch-zoom: ; --tw-scroll-snap-strictness: proximity; --tw-gradient-from-position: ; --tw-gradient-via-position: ; --tw-gradient-to-position: ; --tw-ordinal: ; --tw-slashed-zero: ; --tw-numeric-figure: ; --tw-numeric-spacing: ; --tw-numeric-fraction: ; --tw-ring-inset: ; --tw-ring-offset-width: 0px; --tw-ring-offset-color: #fff; --tw-ring-color: rgba(59,130,246,.5); --tw-ring-offset-shadow: 0 0 #0000; --tw-ring-shadow: 0 0 #0000; --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; --tw-blur: ; --tw-brightness: ; --tw-contrast: ; --tw-grayscale: ; --tw-hue-rotate: ; --tw-invert: ; --tw-saturate: ; --tw-sepia: ; --tw-drop-shadow: ; --tw-backdrop-blur: ; --tw-backdrop-brightness: ; --tw-backdrop-contrast: ; --tw-backdrop-grayscale: ; --tw-backdrop-hue-rotate: ; --tw-backdrop-invert: ; --tw-backdrop-opacity: ; --tw-backdrop-saturate: ; --tw-backdrop-sepia: ; --tw-contain-size: ; --tw-contain-layout: ; --tw-contain-paint: ; --tw-contain-style: ; }

*, ::after, ::before { box-sizing: border-box; border: 0px solid rgb(229, 231, 235); }

::after, ::before { --tw-content: ""; }

:host, html { line-height: 1.5; text-size-adjust: 100%; tab-size: 4; font-family: ui-sans-serif, system-ui, sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji"; font-feature-settings: normal; font-variation-settings: normal; -webkit-tap-highlight-color: transparent; }

body { margin: 0px; line-height: inherit; }

hr { height: 0px; color: inherit; border-top-width: 1px; }

abbr:where([title]) { text-decoration: underline dotted; }

h1, h2, h3, h4, h5, h6 { font-size: inherit; font-weight: inherit; }

a { color: inherit; text-decoration: inherit; }

b, strong { font-weight: bolder; }

code, kbd, pre, samp { font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace; font-feature-settings: normal; font-variation-settings: normal; font-size: 1em; }

small { font-size: 80%; }

sub, sup { font-size: 75%; line-height: 0; position: relative; vertical-align: baseline; }

sub { bottom: -0.25em; }

sup { top: -0.5em; }

table { text-indent: 0px; border-color: inherit; border-collapse: collapse; }

button, input, optgroup, select, textarea { font-family: inherit; font-feature-settings: inherit; font-variation-settings: inherit; font-size: 100%; font-weight: inherit; line-height: inherit; letter-spacing: inherit; color: inherit; margin: 0px; padding: 0px; }

button, select { text-transform: none; }

button, input:where([type="button"]), input:where([type="reset"]), input:where([type="submit"]) { appearance: button; background-color: transparent; background-image: none; }

progress { vertical-align: baseline; }

::-webkit-inner-spin-button, ::-webkit-outer-spin-button { height: auto; }

[type="search"] { appearance: textfield; outline-offset: -2px; }

::-webkit-search-decoration { appearance: none; }

::-webkit-file-upload-button { appearance: button; font: inherit; }

summary { display: list-item; }

blockquote, dd, dl, figure, h1, h2, h3, h4, h5, h6, hr, p, pre { margin: 0px; }

fieldset { margin: 0px; }

fieldset, legend { padding: 0px; }

menu, ol, ul { list-style: none; margin: 0px; padding: 0px; }

dialog { padding: 0px; }

textarea { resize: vertical; }

input::placeholder, textarea::placeholder { opacity: 1; color: rgb(156, 163, 175); }

[role="button"], button { cursor: pointer; }

:disabled { cursor: default; }

audio, canvas, embed, iframe, img, object, svg, video { display: block; vertical-align: middle; }

img, video { max-width: 100%; height: auto; }

[hidden]:where(:not([hidden="until-found"])) { display: none; }

.container { width: 100%; }

@media (min-width: 640px) {
  .container { max-width: 640px; }
}

@media (min-width: 768px) {
  .container { max-width: 768px; }
}

@media (min-width: 1024px) {
  .container { max-width: 1024px; }
}

@media (min-width: 1280px) {
  .container { max-width: 1280px; }
}

@media (min-width: 1536px) {
  .container { max-width: 1536px; }
}

.sr-only { position: absolute; width: 1px; height: 1px; padding: 0px; margin: -1px; overflow: hidden; clip: rect(0px, 0px, 0px, 0px); white-space: nowrap; border-width: 0px; }

.pointer-events-none { pointer-events: none; }

.pointer-events-auto { pointer-events: auto; }

.visible { visibility: visible; }

.invisible { visibility: hidden; }

.fixed { position: fixed; }

.absolute { position: absolute; }

.relative { position: relative; }

.inset-0 { inset: 0px; }

.inset-x-0 { left: 0px; right: 0px; }

.inset-y-0 { top: 0px; bottom: 0px; }

.-bottom-12 { bottom: -3rem; }

.-left-12 { left: -3rem; }

.-right-12 { right: -3rem; }

.-top-12 { top: -3rem; }

.bottom-0 { bottom: 0px; }

.left-0 { left: 0px; }

.left-1 { left: 0.25rem; }

.left-1\/2 { left: 50%; }

.left-2 { left: 0.5rem; }

.left-\[50\%\] { left: 50%; }

.right-0 { right: 0px; }

.right-1 { right: 0.25rem; }

.right-2 { right: 0.5rem; }

.right-3 { right: 0.75rem; }

.right-4 { right: 1rem; }

.top-0 { top: 0px; }

.top-1 { top: 0.25rem; }

.top-1\.5 { top: 0.375rem; }

.top-1\/2 { top: 50%; }

.top-3\.5 { top: 0.875rem; }

.top-4 { top: 1rem; }

.top-\[1px\] { top: 1px; }

.top-\[50\%\] { top: 50%; }

.top-\[60\%\] { top: 60%; }

.top-full { top: 100%; }

.z-10 { z-index: 10; }

.z-20 { z-index: 20; }

.z-50 { z-index: 50; }

.z-\[100\] { z-index: 100; }

.z-\[1\] { z-index: 1; }

.-mx-1 { margin-left: -0.25rem; margin-right: -0.25rem; }

.mx-2 { margin-left: 0.5rem; margin-right: 0.5rem; }

.mx-3\.5 { margin-left: 0.875rem; margin-right: 0.875rem; }

.mx-auto { margin-left: auto; margin-right: auto; }

.my-0\.5 { margin-top: 0.125rem; margin-bottom: 0.125rem; }

.my-1 { margin-top: 0.25rem; margin-bottom: 0.25rem; }

.-ml-4 { margin-left: -1rem; }

.-mt-4 { margin-top: -1rem; }

.mb-1 { margin-bottom: 0.25rem; }

.mb-2 { margin-bottom: 0.5rem; }

.mb-4 { margin-bottom: 1rem; }

.ml-1 { margin-left: 0.25rem; }

.ml-auto { margin-left: auto; }

.mr-2 { margin-right: 0.5rem; }

.mt-1\.5 { margin-top: 0.375rem; }

.mt-2 { margin-top: 0.5rem; }

.mt-24 { margin-top: 6rem; }

.mt-4 { margin-top: 1rem; }

.mt-8 { margin-top: 2rem; }

.mt-auto { margin-top: auto; }

.block { display: block; }

.flex { display: flex; }

.inline-flex { display: inline-flex; }

.table { display: table; }

.grid { display: grid; }

.hidden { display: none; }

.aspect-square { aspect-ratio: 1 / 1; }

.aspect-video { aspect-ratio: 16 / 9; }

.size-4 { width: 1rem; height: 1rem; }

.h-1\.5 { height: 0.375rem; }

.h-10 { height: 2.5rem; }

.h-12 { height: 3rem; }

.h-2 { height: 0.5rem; }

.h-2\.5 { height: 0.625rem; }

.h-3 { height: 0.75rem; }

.h-3\.5 { height: 0.875rem; }

.h-4 { height: 1rem; }

.h-5 { height: 1.25rem; }

.h-7 { height: 1.75rem; }

.h-8 { height: 2rem; }

.h-9 { height: 2.25rem; }

.h-\[1px\] { height: 1px; }

.h-\[calc\(100vh-24rem\)\] { height: calc(-24rem + 100vh); }

.h-\[calc\(100vh-8rem\)\] { height: calc(-8rem + 100vh); }

.h-\[var\(--radix-navigation-menu-viewport-height\)\] { height: var(--radix-navigation-menu-viewport-height); }

.h-\[var\(--radix-select-trigger-height\)\] { height: var(--radix-select-trigger-height); }

.h-auto { height: auto; }

.h-full { height: 100%; }

.h-px { height: 1px; }

.h-svh { height: 100svh; }

.max-h-96 { max-height: 24rem; }

.max-h-\[300px\] { max-height: 300px; }

.max-h-full { max-height: 100%; }

.max-h-screen { max-height: 100vh; }

.min-h-0 { min-height: 0px; }

.min-h-\[60px\] { min-height: 60px; }

.min-h-screen { min-height: 100vh; }

.min-h-svh { min-height: 100svh; }

.w-0 { width: 0px; }

.w-1 { width: 0.25rem; }

.w-10 { width: 2.5rem; }

.w-2 { width: 0.5rem; }

.w-2\.5 { width: 0.625rem; }

.w-3 { width: 0.75rem; }

.w-3\.5 { width: 0.875rem; }

.w-3\/4 { width: 75%; }

.w-4 { width: 1rem; }

.w-5 { width: 1.25rem; }

.w-64 { width: 16rem; }

.w-7 { width: 1.75rem; }

.w-72 { width: 18rem; }

.w-8 { width: 2rem; }

.w-9 { width: 2.25rem; }

.w-\[--sidebar-width\] { width: var(--sidebar-width); }

.w-\[100px\] { width: 100px; }

.w-\[1px\] { width: 1px; }

.w-auto { width: auto; }

.w-full { width: 100%; }

.w-max { width: max-content; }

.w-px { width: 1px; }

.min-w-0 { min-width: 0px; }

.min-w-10 { min-width: 2.5rem; }

.min-w-5 { min-width: 1.25rem; }

.min-w-8 { min-width: 2rem; }

.min-w-9 { min-width: 2.25rem; }

.min-w-\[12rem\] { min-width: 12rem; }

.min-w-\[8rem\] { min-width: 8rem; }

.min-w-\[var\(--radix-select-trigger-width\)\] { min-width: var(--radix-select-trigger-width); }

.max-w-3xl { max-width: 48rem; }

.max-w-\[--skeleton-width\] { max-width: var(--skeleton-width); }

.max-w-lg { max-width: 32rem; }

.max-w-max { max-width: max-content; }

.flex-1 { flex: 1 1 0%; }

.shrink-0 { flex-shrink: 0; }

.grow { flex-grow: 1; }

.grow-0 { flex-grow: 0; }

.basis-full { flex-basis: 100%; }

.caption-bottom { caption-side: bottom; }

.border-collapse { border-collapse: collapse; }

.-translate-x-1\/2 { --tw-translate-x: -50%; }

.-translate-x-1\/2, .-translate-x-px { transform: translate(var(--tw-translate-x),var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y)); }

.-translate-x-px { --tw-translate-x: -1px; }

.-translate-y-1\/2 { --tw-translate-y: -50%; }

.-translate-y-1\/2, .translate-x-\[-50\%\] { transform: translate(var(--tw-translate-x),var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y)); }

.translate-x-\[-50\%\] { --tw-translate-x: -50%; }

.translate-x-px { --tw-translate-x: 1px; }

.translate-x-px, .translate-y-\[-50\%\] { transform: translate(var(--tw-translate-x),var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y)); }

.translate-y-\[-50\%\] { --tw-translate-y: -50%; }

.rotate-45 { --tw-rotate: 45deg; }

.rotate-45, .rotate-90 { transform: translate(var(--tw-translate-x),var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y)); }

.rotate-90 { --tw-rotate: 90deg; }

.transform { transform: translate(var(--tw-translate-x),var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y)); }

@keyframes pulse { 
  50% { opacity: 0.5; }
}

.animate-pulse { animation: 2s cubic-bezier(0.4, 0, 0.6, 1) 0s infinite normal none running pulse; }

.cursor-default { cursor: default; }

.cursor-pointer { cursor: pointer; }

.touch-none { touch-action: none; }

.select-none { user-select: none; }

.resize { resize: both; }

.list-none { list-style-type: none; }

.flex-row { flex-direction: row; }

.flex-col { flex-direction: column; }

.flex-col-reverse { flex-direction: column-reverse; }

.flex-wrap { flex-wrap: wrap; }

.items-start { align-items: flex-start; }

.items-end { align-items: flex-end; }

.items-center { align-items: center; }

.items-stretch { align-items: stretch; }

.justify-end { justify-content: flex-end; }

.justify-center { justify-content: center; }

.justify-between { justify-content: space-between; }

.gap-1 { gap: 0.25rem; }

.gap-1\.5 { gap: 0.375rem; }

.gap-2 { gap: 0.5rem; }

.gap-4 { gap: 1rem; }

.space-x-1 > :not([hidden]) ~ :not([hidden]) { --tw-space-x-reverse: 0; margin-right: calc(.25rem * var(--tw-space-x-reverse)); margin-left: calc(.25rem * calc(1 - var(--tw-space-x-reverse))); }

.space-x-2 > :not([hidden]) ~ :not([hidden]) { --tw-space-x-reverse: 0; margin-right: calc(.5rem * var(--tw-space-x-reverse)); margin-left: calc(.5rem * calc(1 - var(--tw-space-x-reverse))); }

.space-x-4 > :not([hidden]) ~ :not([hidden]) { --tw-space-x-reverse: 0; margin-right: calc(1rem * var(--tw-space-x-reverse)); margin-left: calc(1rem * calc(1 - var(--tw-space-x-reverse))); }

.space-y-1 > :not([hidden]) ~ :not([hidden]) { --tw-space-y-reverse: 0; margin-top: calc(.25rem * calc(1 - var(--tw-space-y-reverse))); margin-bottom: calc(.25rem * var(--tw-space-y-reverse)); }

.space-y-1\.5 > :not([hidden]) ~ :not([hidden]) { --tw-space-y-reverse: 0; margin-top: calc(.375rem * calc(1 - var(--tw-space-y-reverse))); margin-bottom: calc(.375rem * var(--tw-space-y-reverse)); }

.space-y-2 > :not([hidden]) ~ :not([hidden]) { --tw-space-y-reverse: 0; margin-top: calc(.5rem * calc(1 - var(--tw-space-y-reverse))); margin-bottom: calc(.5rem * var(--tw-space-y-reverse)); }

.space-y-4 > :not([hidden]) ~ :not([hidden]) { --tw-space-y-reverse: 0; margin-top: calc(1rem * calc(1 - var(--tw-space-y-reverse))); margin-bottom: calc(1rem * var(--tw-space-y-reverse)); }

.overflow-auto { overflow: auto; }

.overflow-hidden { overflow: hidden; }

.overflow-y-auto { overflow-y: auto; }

.overflow-x-hidden { overflow-x: hidden; }

.whitespace-nowrap { white-space: nowrap; }

.break-words { overflow-wrap: break-word; }

.rounded { border-radius: 0.25rem; }

.rounded-\[2px\] { border-radius: 2px; }

.rounded-\[inherit\] { border-radius: inherit; }

.rounded-full { border-radius: 9999px; }

.rounded-lg { border-radius: var(--radius); }

.rounded-md { border-radius: calc(var(--radius) - 2px); }

.rounded-sm { border-radius: calc(var(--radius) - 4px); }

.rounded-xl { border-radius: 0.75rem; }

.rounded-t-\[10px\] { border-top-left-radius: 10px; border-top-right-radius: 10px; }

.rounded-tl-sm { border-top-left-radius: calc(var(--radius) - 4px); }

.border { border-width: 1px; }

.border-2 { border-width: 2px; }

.border-\[1\.5px\] { border-width: 1.5px; }

.border-y { border-top-width: 1px; }

.border-b, .border-y { border-bottom-width: 1px; }

.border-l { border-left-width: 1px; }

.border-r { border-right-width: 1px; }

.border-t { border-top-width: 1px; }

.border-dashed { border-style: dashed; }

.border-\[--color-border\] { border-color: var(--color-border); }

.border-border\/50 { border-color: hsl(var(--border)/.5); }

.border-destructive { border-color: hsl(var(--destructive)); }

.border-destructive\/50 { border-color: hsl(var(--destructive)/.5); }

.border-gray-700 { --tw-border-opacity: 1; border-color: rgb(55 65 81/var(--tw-border-opacity,1)); }

.border-gray-800 { --tw-border-opacity: 1; border-color: rgb(31 41 55/var(--tw-border-opacity,1)); }

.border-input { border-color: hsl(var(--input)); }

.border-primary { border-color: hsl(var(--primary)); }

.border-primary\/50 { border-color: hsl(var(--primary)/.5); }

.border-sidebar-border { border-color: hsl(var(--sidebar-border)); }

.border-transparent { border-color: transparent; }

.border-l-transparent { border-left-color: transparent; }

.border-t-transparent { border-top-color: transparent; }

.bg-\[\#121212\] { --tw-bg-opacity: 1; background-color: rgb(18 18 18/var(--tw-bg-opacity,1)); }

.bg-\[\#1a5b8e\] { --tw-bg-opacity: 1; background-color: rgb(26 91 142/var(--tw-bg-opacity,1)); }

.bg-\[\#2e7d32\] { --tw-bg-opacity: 1; background-color: rgb(46 125 50/var(--tw-bg-opacity,1)); }

.bg-\[\#ff6b35\] { --tw-bg-opacity: 1; background-color: rgb(255 107 53/var(--tw-bg-opacity,1)); }

.bg-\[--color-bg\] { background-color: var(--color-bg); }

.bg-accent { background-color: hsl(var(--accent)); }

.bg-background { background-color: hsl(var(--background)); }

.bg-black { --tw-bg-opacity: 1; background-color: rgb(0 0 0/var(--tw-bg-opacity,1)); }

.bg-black\/80 { background-color: rgba(0, 0, 0, 0.8); }

.bg-border { background-color: hsl(var(--border)); }

.bg-card { background-color: hsl(var(--card)); }

.bg-destructive { background-color: hsl(var(--destructive)); }

.bg-foreground { background-color: hsl(var(--foreground)); }

.bg-gray-600 { --tw-bg-opacity: 1; background-color: rgb(75 85 99/var(--tw-bg-opacity,1)); }

.bg-gray-700 { --tw-bg-opacity: 1; background-color: rgb(55 65 81/var(--tw-bg-opacity,1)); }

.bg-gray-800 { --tw-bg-opacity: 1; background-color: rgb(31 41 55/var(--tw-bg-opacity,1)); }

.bg-gray-900 { --tw-bg-opacity: 1; background-color: rgb(17 24 39/var(--tw-bg-opacity,1)); }

.bg-muted { background-color: hsl(var(--muted)); }

.bg-muted\/50 { background-color: hsl(var(--muted)/.5); }

.bg-popover { background-color: hsl(var(--popover)); }

.bg-primary { background-color: hsl(var(--primary)); }

.bg-primary\/10 { background-color: hsl(var(--primary)/.1); }

.bg-primary\/20 { background-color: hsl(var(--primary)/.2); }

.bg-secondary { background-color: hsl(var(--secondary)); }

.bg-sidebar { background-color: hsl(var(--sidebar-background)); }

.bg-sidebar-border { background-color: hsl(var(--sidebar-border)); }

.bg-transparent { background-color: transparent; }

.bg-opacity-50 { --tw-bg-opacity: 0.5; }

.fill-current { fill: currentcolor; }

.fill-primary { fill: hsl(var(--primary)); }

.p-0 { padding: 0px; }

.p-1 { padding: 0.25rem; }

.p-2 { padding: 0.5rem; }

.p-3 { padding: 0.75rem; }

.p-4 { padding: 1rem; }

.p-6 { padding: 1.5rem; }

.p-\[1px\] { padding: 1px; }

.px-1 { padding-left: 0.25rem; padding-right: 0.25rem; }

.px-1\.5 { padding-left: 0.375rem; padding-right: 0.375rem; }

.px-2 { padding-left: 0.5rem; padding-right: 0.5rem; }

.px-2\.5 { padding-left: 0.625rem; padding-right: 0.625rem; }

.px-3 { padding-left: 0.75rem; padding-right: 0.75rem; }

.px-4 { padding-left: 1rem; padding-right: 1rem; }

.px-8 { padding-left: 2rem; padding-right: 2rem; }

.py-0\.5 { padding-top: 0.125rem; padding-bottom: 0.125rem; }

.py-1 { padding-top: 0.25rem; padding-bottom: 0.25rem; }

.py-1\.5 { padding-top: 0.375rem; padding-bottom: 0.375rem; }

.py-2 { padding-top: 0.5rem; padding-bottom: 0.5rem; }

.py-3 { padding-top: 0.75rem; padding-bottom: 0.75rem; }

.py-4 { padding-top: 1rem; padding-bottom: 1rem; }

.py-6 { padding-top: 1.5rem; padding-bottom: 1.5rem; }

.pb-3 { padding-bottom: 0.75rem; }

.pb-4 { padding-bottom: 1rem; }

.pl-2 { padding-left: 0.5rem; }

.pl-2\.5 { padding-left: 0.625rem; }

.pl-4 { padding-left: 1rem; }

.pl-8 { padding-left: 2rem; }

.pr-2 { padding-right: 0.5rem; }

.pr-2\.5 { padding-right: 0.625rem; }

.pr-6 { padding-right: 1.5rem; }

.pr-8 { padding-right: 2rem; }

.pt-0 { padding-top: 0px; }

.pt-1 { padding-top: 0.25rem; }

.pt-3 { padding-top: 0.75rem; }

.pt-4 { padding-top: 1rem; }

.text-left { text-align: left; }

.text-center { text-align: center; }

.align-middle { vertical-align: middle; }

.font-mono { font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace; }

.text-2xl { font-size: 1.5rem; line-height: 2rem; }

.text-\[0\.8rem\] { font-size: 0.8rem; }

.text-base { font-size: 1rem; line-height: 1.5rem; }

.text-lg { font-size: 1.125rem; line-height: 1.75rem; }

.text-sm { font-size: 0.875rem; line-height: 1.25rem; }

.text-xl { font-size: 1.25rem; line-height: 1.75rem; }

.text-xs { font-size: 0.75rem; line-height: 1rem; }

.font-bold { font-weight: 700; }

.font-medium { font-weight: 500; }

.font-normal { font-weight: 400; }

.font-semibold { font-weight: 600; }

.tabular-nums { --tw-numeric-spacing: tabular-nums; font-variant-numeric: var(--tw-ordinal) var(--tw-slashed-zero) var(--tw-numeric-figure) var(--tw-numeric-spacing) var(--tw-numeric-fraction); }

.leading-none { line-height: 1; }

.tracking-tight { letter-spacing: -0.025em; }

.tracking-widest { letter-spacing: 0.1em; }

.text-\[\#007d8c\] { --tw-text-opacity: 1; color: rgb(0 125 140/var(--tw-text-opacity,1)); }

.text-\[\#ff6b35\] { --tw-text-opacity: 1; color: rgb(255 107 53/var(--tw-text-opacity,1)); }

.text-accent-foreground { color: hsl(var(--accent-foreground)); }

.text-card-foreground { color: hsl(var(--card-foreground)); }

.text-current { color: currentcolor; }

.text-destructive { color: hsl(var(--destructive)); }

.text-destructive-foreground { color: hsl(var(--destructive-foreground)); }

.text-foreground { color: hsl(var(--foreground)); }

.text-foreground\/50 { color: hsl(var(--foreground)/.5); }

.text-gray-400 { --tw-text-opacity: 1; color: rgb(156 163 175/var(--tw-text-opacity,1)); }

.text-muted-foreground { color: hsl(var(--muted-foreground)); }

.text-popover-foreground { color: hsl(var(--popover-foreground)); }

.text-primary { color: hsl(var(--primary)); }

.text-primary-foreground { color: hsl(var(--primary-foreground)); }

.text-red-500 { --tw-text-opacity: 1; color: rgb(239 68 68/var(--tw-text-opacity,1)); }

.text-secondary-foreground { color: hsl(var(--secondary-foreground)); }

.text-sidebar-foreground { color: hsl(var(--sidebar-foreground)); }

.text-sidebar-foreground\/70 { color: hsl(var(--sidebar-foreground)/.7); }

.text-white { --tw-text-opacity: 1; color: rgb(255 255 255/var(--tw-text-opacity,1)); }

.text-yellow-500 { --tw-text-opacity: 1; color: rgb(234 179 8/var(--tw-text-opacity,1)); }

.underline-offset-4 { text-underline-offset: 4px; }

.antialiased { -webkit-font-smoothing: antialiased; }

.opacity-0 { opacity: 0; }

.opacity-50 { opacity: 0.5; }

.opacity-60 { opacity: 0.6; }

.opacity-70 { opacity: 0.7; }

.opacity-90 { opacity: 0.9; }

.shadow { --tw-shadow: 0 1px 3px 0 rgba(0,0,0,.1),0 1px 2px -1px rgba(0,0,0,.1); --tw-shadow-colored: 0 1px 3px 0 var(--tw-shadow-color),0 1px 2px -1px var(--tw-shadow-color); }

.shadow, .shadow-\[0_0_0_1px_hsl\(var\(--sidebar-border\)\)\] { box-shadow: var(--tw-ring-offset-shadow,0 0 #0000),var(--tw-ring-shadow,0 0 #0000),var(--tw-shadow); }

.shadow-\[0_0_0_1px_hsl\(var\(--sidebar-border\)\)\] { --tw-shadow: 0 0 0 1px hsl(var(--sidebar-border)); --tw-shadow-colored: 0 0 0 1px var(--tw-shadow-color); }

.shadow-lg { --tw-shadow: 0 10px 15px -3px rgba(0,0,0,.1),0 4px 6px -4px rgba(0,0,0,.1); --tw-shadow-colored: 0 10px 15px -3px var(--tw-shadow-color),0 4px 6px -4px var(--tw-shadow-color); }

.shadow-lg, .shadow-md { box-shadow: var(--tw-ring-offset-shadow,0 0 #0000),var(--tw-ring-shadow,0 0 #0000),var(--tw-shadow); }

.shadow-md { --tw-shadow: 0 4px 6px -1px rgba(0,0,0,.1),0 2px 4px -2px rgba(0,0,0,.1); --tw-shadow-colored: 0 4px 6px -1px var(--tw-shadow-color),0 2px 4px -2px var(--tw-shadow-color); }

.shadow-none { --tw-shadow: 0 0 #0000; --tw-shadow-colored: 0 0 #0000; }

.shadow-none, .shadow-sm { box-shadow: var(--tw-ring-offset-shadow,0 0 #0000),var(--tw-ring-shadow,0 0 #0000),var(--tw-shadow); }

.shadow-sm { --tw-shadow: 0 1px 2px 0 rgba(0,0,0,.05); --tw-shadow-colored: 0 1px 2px 0 var(--tw-shadow-color); }

.shadow-xl { --tw-shadow: 0 20px 25px -5px rgba(0,0,0,.1),0 8px 10px -6px rgba(0,0,0,.1); --tw-shadow-colored: 0 20px 25px -5px var(--tw-shadow-color),0 8px 10px -6px var(--tw-shadow-color); box-shadow: var(--tw-ring-offset-shadow,0 0 #0000),var(--tw-ring-shadow,0 0 #0000),var(--tw-shadow); }

.outline-none { outline: transparent solid 2px; outline-offset: 2px; }

.outline { outline-style: solid; }

.ring-0 { --tw-ring-offset-shadow: var(--tw-ring-inset) 0 0 0 var(--tw-ring-offset-width) var(--tw-ring-offset-color); --tw-ring-shadow: var(--tw-ring-inset) 0 0 0 calc(0px + var(--tw-ring-offset-width)) var(--tw-ring-color); }

.ring-0, .ring-1 { box-shadow: var(--tw-ring-offset-shadow),var(--tw-ring-shadow),var(--tw-shadow,0 0 #0000); }

.ring-1 { --tw-ring-offset-shadow: var(--tw-ring-inset) 0 0 0 var(--tw-ring-offset-width) var(--tw-ring-offset-color); --tw-ring-shadow: var(--tw-ring-inset) 0 0 0 calc(1px + var(--tw-ring-offset-width)) var(--tw-ring-color); }

.ring-ring { --tw-ring-color: hsl(var(--ring)); }

.ring-sidebar-ring { --tw-ring-color: hsl(var(--sidebar-ring)); }

.ring-offset-background { --tw-ring-offset-color: hsl(var(--background)); }

.filter { filter: var(--tw-blur) var(--tw-brightness) var(--tw-contrast) var(--tw-grayscale) var(--tw-hue-rotate) var(--tw-invert) var(--tw-saturate) var(--tw-sepia) var(--tw-drop-shadow); }

.transition { transition-property: color, background-color, border-color, text-decoration-color, fill, stroke, opacity, box-shadow, transform, filter, backdrop-filter; transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1); transition-duration: 0.15s; }

.transition-\[left\,right\,width\] { transition-property: left, right, width; transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1); transition-duration: 0.15s; }

.transition-\[margin\,opa\] { transition-property: margin, opa; transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1); transition-duration: 0.15s; }

.transition-\[width\,height\,padding\] { transition-property: width, height, padding; transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1); transition-duration: 0.15s; }

.transition-\[width\] { transition-property: width; transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1); transition-duration: 0.15s; }

.transition-all { transition-property: all; transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1); transition-duration: 0.15s; }

.transition-colors { transition-property: color, background-color, border-color, text-decoration-color, fill, stroke; transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1); transition-duration: 0.15s; }

.transition-opacity { transition-property: opacity; transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1); transition-duration: 0.15s; }

.transition-transform { transition-property: transform; transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1); transition-duration: 0.15s; }

.duration-1000 { transition-duration: 1s; }

.duration-200 { transition-duration: 0.2s; }

.duration-300 { transition-duration: 0.3s; }

.ease-in-out { transition-timing-function: cubic-bezier(0.4, 0, 0.2, 1); }

.ease-linear { transition-timing-function: linear; }

@keyframes enter { 
  0% { opacity: var(--tw-enter-opacity,1); transform: translate3d(var(--tw-enter-translate-x,0),var(--tw-enter-translate-y,0),0) scale3d(var(--tw-enter-scale,1),var(--tw-enter-scale,1),var(--tw-enter-scale,1)) rotate(var(--tw-enter-rotate,0)); }
}

@keyframes exit { 
  100% { opacity: var(--tw-exit-opacity,1); transform: translate3d(var(--tw-exit-translate-x,0),var(--tw-exit-translate-y,0),0) scale3d(var(--tw-exit-scale,1),var(--tw-exit-scale,1),var(--tw-exit-scale,1)) rotate(var(--tw-exit-rotate,0)); }
}

.animate-in { animation-name: enter; animation-duration: 0.15s; --tw-enter-opacity: initial; --tw-enter-scale: initial; --tw-enter-rotate: initial; --tw-enter-translate-x: initial; --tw-enter-translate-y: initial; }

.fade-in-0 { --tw-enter-opacity: 0; }

.zoom-in-95 { --tw-enter-scale: .95; }

.duration-1000 { animation-duration: 1s; }

.duration-200 { animation-duration: 0.2s; }

.duration-300 { animation-duration: 0.3s; }

.ease-in-out { animation-timing-function: cubic-bezier(0.4, 0, 0.2, 1); }

.ease-linear { animation-timing-function: linear; }

:root { --primary-orange: #ff6b35; --primary-blue: #1a5b8e; --primary-teal: #007d8c; --secondary-purple: #6a1b9a; --secondary-green: #2e7d32; --dark: #121212; }

body { color: rgb(255, 255, 255); background-color: var(--dark); }

.terminal-container { border-radius: 0.375rem; overflow: hidden; }

.xterm { padding: 0.5rem; }

.file-explorer::-webkit-scrollbar { width: 8px; }

.file-explorer::-webkit-scrollbar-track { background: rgb(30, 30, 30); }

.file-explorer::-webkit-scrollbar-thumb { background-color: rgb(68, 68, 68); border-radius: 4px; }

.file-explorer::-webkit-scrollbar-thumb:hover { background-color: rgb(85, 85, 85); }

.file\:border-0::file-selector-button { border-width: 0px; }

.file\:bg-transparent::file-selector-button { background-color: transparent; }

.file\:text-sm::file-selector-button { font-size: 0.875rem; line-height: 1.25rem; }

.file\:font-medium::file-selector-button { font-weight: 500; }

.file\:text-foreground::file-selector-button { color: hsl(var(--foreground)); }

.placeholder\:text-muted-foreground::placeholder { color: hsl(var(--muted-foreground)); }

.after\:absolute::after { content: var(--tw-content); position: absolute; }

.after\:-inset-2::after { content: var(--tw-content); inset: -0.5rem; }

.after\:inset-y-0::after { content: var(--tw-content); top: 0px; bottom: 0px; }

.after\:left-1\/2::after { content: var(--tw-content); left: 50%; }

.after\:w-1::after { content: var(--tw-content); width: 0.25rem; }

.after\:w-\[2px\]::after { content: var(--tw-content); width: 2px; }

.after\:-translate-x-1\/2::after { content: var(--tw-content); --tw-translate-x: -50%; transform: translate(var(--tw-translate-x),var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y)); }

.first\:rounded-l-md:first-child { border-top-left-radius: calc(var(--radius) - 2px); border-bottom-left-radius: calc(var(--radius) - 2px); }

.first\:border-l:first-child { border-left-width: 1px; }

.last\:rounded-r-md:last-child { border-top-right-radius: calc(var(--radius) - 2px); border-bottom-right-radius: calc(var(--radius) - 2px); }

.focus-within\:relative:focus-within { position: relative; }

.focus-within\:z-20:focus-within { z-index: 20; }

.hover\:bg-accent:hover { background-color: hsl(var(--accent)); }

.hover\:bg-destructive\/80:hover { background-color: hsl(var(--destructive)/.8); }

.hover\:bg-destructive\/90:hover { background-color: hsl(var(--destructive)/.9); }

.hover\:bg-gray-700:hover { --tw-bg-opacity: 1; background-color: rgb(55 65 81/var(--tw-bg-opacity,1)); }

.hover\:bg-gray-800:hover { --tw-bg-opacity: 1; background-color: rgb(31 41 55/var(--tw-bg-opacity,1)); }

.hover\:bg-muted:hover { background-color: hsl(var(--muted)); }

.hover\:bg-muted\/50:hover { background-color: hsl(var(--muted)/.5); }

.hover\:bg-primary:hover { background-color: hsl(var(--primary)); }

.hover\:bg-primary\/80:hover { background-color: hsl(var(--primary)/.8); }

.hover\:bg-primary\/90:hover { background-color: hsl(var(--primary)/.9); }

.hover\:bg-secondary:hover { background-color: hsl(var(--secondary)); }

.hover\:bg-secondary\/80:hover { background-color: hsl(var(--secondary)/.8); }

.hover\:bg-sidebar-accent:hover { background-color: hsl(var(--sidebar-accent)); }

.hover\:bg-opacity-90:hover { --tw-bg-opacity: 0.9; }

.hover\:text-accent-foreground:hover { color: hsl(var(--accent-foreground)); }

.hover\:text-foreground:hover { color: hsl(var(--foreground)); }

.hover\:text-muted-foreground:hover { color: hsl(var(--muted-foreground)); }

.hover\:text-primary-foreground:hover { color: hsl(var(--primary-foreground)); }

.hover\:text-sidebar-accent-foreground:hover { color: hsl(var(--sidebar-accent-foreground)); }

.hover\:underline:hover { text-decoration-line: underline; }

.hover\:opacity-100:hover { opacity: 1; }

.hover\:shadow-\[0_0_0_1px_hsl\(var\(--sidebar-accent\)\)\]:hover { --tw-shadow: 0 0 0 1px hsl(var(--sidebar-accent)); --tw-shadow-colored: 0 0 0 1px var(--tw-shadow-color); box-shadow: var(--tw-ring-offset-shadow,0 0 #0000),var(--tw-ring-shadow,0 0 #0000),var(--tw-shadow); }

.hover\:after\:bg-sidebar-border:hover::after { content: var(--tw-content); background-color: hsl(var(--sidebar-border)); }

.focus\:bg-accent:focus { background-color: hsl(var(--accent)); }

.focus\:bg-primary:focus { background-color: hsl(var(--primary)); }

.focus\:text-accent-foreground:focus { color: hsl(var(--accent-foreground)); }

.focus\:text-primary-foreground:focus { color: hsl(var(--primary-foreground)); }

.focus\:opacity-100:focus { opacity: 1; }

.focus\:outline-none:focus { outline: transparent solid 2px; outline-offset: 2px; }

.focus\:ring-1:focus { --tw-ring-offset-shadow: var(--tw-ring-inset) 0 0 0 var(--tw-ring-offset-width) var(--tw-ring-offset-color); --tw-ring-shadow: var(--tw-ring-inset) 0 0 0 calc(1px + var(--tw-ring-offset-width)) var(--tw-ring-color); }

.focus\:ring-1:focus, .focus\:ring-2:focus { box-shadow: var(--tw-ring-offset-shadow),var(--tw-ring-shadow),var(--tw-shadow,0 0 #0000); }

.focus\:ring-2:focus { --tw-ring-offset-shadow: var(--tw-ring-inset) 0 0 0 var(--tw-ring-offset-width) var(--tw-ring-offset-color); --tw-ring-shadow: var(--tw-ring-inset) 0 0 0 calc(2px + var(--tw-ring-offset-width)) var(--tw-ring-color); }

.focus\:ring-ring:focus { --tw-ring-color: hsl(var(--ring)); }

.focus\:ring-offset-2:focus { --tw-ring-offset-width: 2px; }

.focus-visible\:outline-none:focus-visible { outline: transparent solid 2px; outline-offset: 2px; }

.focus-visible\:ring-1:focus-visible { --tw-ring-offset-shadow: var(--tw-ring-inset) 0 0 0 var(--tw-ring-offset-width) var(--tw-ring-offset-color); --tw-ring-shadow: var(--tw-ring-inset) 0 0 0 calc(1px + var(--tw-ring-offset-width)) var(--tw-ring-color); box-shadow: var(--tw-ring-offset-shadow),var(--tw-ring-shadow),var(--tw-shadow,0 0 #0000); }

.focus-visible\:ring-2:focus-visible { --tw-ring-offset-shadow: var(--tw-ring-inset) 0 0 0 var(--tw-ring-offset-width) var(--tw-ring-offset-color); --tw-ring-shadow: var(--tw-ring-inset) 0 0 0 calc(2px + var(--tw-ring-offset-width)) var(--tw-ring-color); box-shadow: var(--tw-ring-offset-shadow),var(--tw-ring-shadow),var(--tw-shadow,0 0 #0000); }

.focus-visible\:ring-ring:focus-visible { --tw-ring-color: hsl(var(--ring)); }

.focus-visible\:ring-sidebar-ring:focus-visible { --tw-ring-color: hsl(var(--sidebar-ring)); }

.focus-visible\:ring-offset-1:focus-visible { --tw-ring-offset-width: 1px; }

.focus-visible\:ring-offset-2:focus-visible { --tw-ring-offset-width: 2px; }

.focus-visible\:ring-offset-background:focus-visible { --tw-ring-offset-color: hsl(var(--background)); }

.active\:bg-sidebar-accent:active { background-color: hsl(var(--sidebar-accent)); }

.active\:text-sidebar-accent-foreground:active { color: hsl(var(--sidebar-accent-foreground)); }

.disabled\:pointer-events-none:disabled { pointer-events: none; }

.disabled\:cursor-not-allowed:disabled { cursor: not-allowed; }

.disabled\:opacity-50:disabled { opacity: 0.5; }

.group\/menu-item:focus-within .group-focus-within\/menu-item\:opacity-100 { opacity: 1; }

.group:hover .group-hover\:opacity-100, .group\/menu-item:hover .group-hover\/menu-item\:opacity-100 { opacity: 1; }

.group.destructive .group-\[\.destructive\]\:border-muted\/40 { border-color: hsl(var(--muted)/.4); }

.group.toaster .group-\[\.toaster\]\:border-border { border-color: hsl(var(--border)); }

.group.toast .group-\[\.toast\]\:bg-muted { background-color: hsl(var(--muted)); }

.group.toast .group-\[\.toast\]\:bg-primary { background-color: hsl(var(--primary)); }

.group.toaster .group-\[\.toaster\]\:bg-background { background-color: hsl(var(--background)); }

.group.destructive .group-\[\.destructive\]\:text-red-300 { --tw-text-opacity: 1; color: rgb(252 165 165/var(--tw-text-opacity,1)); }

.group.toast .group-\[\.toast\]\:text-muted-foreground { color: hsl(var(--muted-foreground)); }

.group.toast .group-\[\.toast\]\:text-primary-foreground { color: hsl(var(--primary-foreground)); }

.group.toaster .group-\[\.toaster\]\:text-foreground { color: hsl(var(--foreground)); }

.group.toaster .group-\[\.toaster\]\:shadow-lg { --tw-shadow: 0 10px 15px -3px rgba(0,0,0,.1),0 4px 6px -4px rgba(0,0,0,.1); --tw-shadow-colored: 0 10px 15px -3px var(--tw-shadow-color),0 4px 6px -4px var(--tw-shadow-color); box-shadow: var(--tw-ring-offset-shadow,0 0 #0000),var(--tw-ring-shadow,0 0 #0000),var(--tw-shadow); }

.group.destructive .group-\[\.destructive\]\:hover\:border-destructive\/30:hover { border-color: hsl(var(--destructive)/.3); }

.group.destructive .group-\[\.destructive\]\:hover\:bg-destructive:hover { background-color: hsl(var(--destructive)); }

.group.destructive .group-\[\.destructive\]\:hover\:text-destructive-foreground:hover { color: hsl(var(--destructive-foreground)); }

.group.destructive .group-\[\.destructive\]\:hover\:text-red-50:hover { --tw-text-opacity: 1; color: rgb(254 242 242/var(--tw-text-opacity,1)); }

.group.destructive .group-\[\.destructive\]\:focus\:ring-destructive:focus { --tw-ring-color: hsl(var(--destructive)); }

.group.destructive .group-\[\.destructive\]\:focus\:ring-red-400:focus { --tw-ring-opacity: 1; --tw-ring-color: rgb(248 113 113/var(--tw-ring-opacity,1)); }

.group.destructive .group-\[\.destructive\]\:focus\:ring-offset-red-600:focus { --tw-ring-offset-color: #dc2626; }

.peer\/menu-button:hover ~ .peer-hover\/menu-button\:text-sidebar-accent-foreground { color: hsl(var(--sidebar-accent-foreground)); }

.peer:disabled ~ .peer-disabled\:cursor-not-allowed { cursor: not-allowed; }

.peer:disabled ~ .peer-disabled\:opacity-70 { opacity: 0.7; }

.has-\[\[data-variant\=inset\]\]\:bg-sidebar:has([data-variant="inset"]) { background-color: hsl(var(--sidebar-background)); }

.has-\[\:disabled\]\:opacity-50:has(:disabled) { opacity: 0.5; }

.group\/menu-item:has([data-sidebar="menu-action"]) .group-has-\[\[data-sidebar\=menu-action\]\]\/menu-item\:pr-8 { padding-right: 2rem; }

.aria-disabled\:pointer-events-none[aria-disabled="true"] { pointer-events: none; }

.aria-disabled\:opacity-50[aria-disabled="true"] { opacity: 0.5; }

.aria-selected\:bg-accent[aria-selected="true"] { background-color: hsl(var(--accent)); }

.aria-selected\:bg-accent\/50[aria-selected="true"] { background-color: hsl(var(--accent)/.5); }

.aria-selected\:text-accent-foreground[aria-selected="true"] { color: hsl(var(--accent-foreground)); }

.aria-selected\:text-muted-foreground[aria-selected="true"] { color: hsl(var(--muted-foreground)); }

.aria-selected\:opacity-100[aria-selected="true"] { opacity: 1; }

.data-\[disabled\=true\]\:pointer-events-none[data-disabled="true"], .data-\[disabled\]\:pointer-events-none[data-disabled] { pointer-events: none; }

.data-\[panel-group-direction\=vertical\]\:h-px[data-panel-group-direction="vertical"] { height: 1px; }

.data-\[panel-group-direction\=vertical\]\:w-full[data-panel-group-direction="vertical"] { width: 100%; }

.data-\[side\=bottom\]\:translate-y-1[data-side="bottom"] { --tw-translate-y: 0.25rem; }

.data-\[side\=bottom\]\:translate-y-1[data-side="bottom"], .data-\[side\=left\]\:-translate-x-1[data-side="left"] { transform: translate(var(--tw-translate-x),var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y)); }

.data-\[side\=left\]\:-translate-x-1[data-side="left"] { --tw-translate-x: -0.25rem; }

.data-\[side\=right\]\:translate-x-1[data-side="right"] { --tw-translate-x: 0.25rem; }

.data-\[side\=right\]\:translate-x-1[data-side="right"], .data-\[side\=top\]\:-translate-y-1[data-side="top"] { transform: translate(var(--tw-translate-x),var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y)); }

.data-\[side\=top\]\:-translate-y-1[data-side="top"] { --tw-translate-y: -0.25rem; }

.data-\[state\=checked\]\:translate-x-4[data-state="checked"] { --tw-translate-x: 1rem; transform: translate(var(--tw-translate-x),var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y)); }

.data-\[state\=unchecked\]\:translate-x-0[data-state="unchecked"], .data-\[swipe\=cancel\]\:translate-x-0[data-swipe="cancel"] { --tw-translate-x: 0px; transform: translate(var(--tw-translate-x),var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y)); }

.data-\[swipe\=end\]\:translate-x-\[var\(--radix-toast-swipe-end-x\)\][data-swipe="end"] { --tw-translate-x: var(--radix-toast-swipe-end-x); }

.data-\[swipe\=end\]\:translate-x-\[var\(--radix-toast-swipe-end-x\)\][data-swipe="end"], .data-\[swipe\=move\]\:translate-x-\[var\(--radix-toast-swipe-move-x\)\][data-swipe="move"] { transform: translate(var(--tw-translate-x),var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y)); }

.data-\[swipe\=move\]\:translate-x-\[var\(--radix-toast-swipe-move-x\)\][data-swipe="move"] { --tw-translate-x: var(--radix-toast-swipe-move-x); }

@keyframes accordion-up { 
  0% { height: var(--radix-accordion-content-height); }
  100% { height: 0px; }
}

.data-\[state\=closed\]\:animate-accordion-up[data-state="closed"] { animation: 0.2s ease-out 0s 1 normal none running accordion-up; }

@keyframes accordion-down { 
  0% { height: 0px; }
  100% { height: var(--radix-accordion-content-height); }
}

.data-\[state\=open\]\:animate-accordion-down[data-state="open"] { animation: 0.2s ease-out 0s 1 normal none running accordion-down; }

.data-\[panel-group-direction\=vertical\]\:flex-col[data-panel-group-direction="vertical"] { flex-direction: column; }

.data-\[active\=true\]\:bg-sidebar-accent[data-active="true"] { background-color: hsl(var(--sidebar-accent)); }

.data-\[active\]\:bg-accent\/50[data-active] { background-color: hsl(var(--accent)/.5); }

.data-\[selected\=true\]\:bg-accent[data-selected="true"] { background-color: hsl(var(--accent)); }

.data-\[state\=active\]\:bg-background[data-state="active"] { background-color: hsl(var(--background)); }

.data-\[state\=checked\]\:bg-primary[data-state="checked"] { background-color: hsl(var(--primary)); }

.data-\[state\=on\]\:bg-accent[data-state="on"], .data-\[state\=open\]\:bg-accent[data-state="open"] { background-color: hsl(var(--accent)); }

.data-\[state\=open\]\:bg-accent\/50[data-state="open"] { background-color: hsl(var(--accent)/.5); }

.data-\[state\=open\]\:bg-secondary[data-state="open"] { background-color: hsl(var(--secondary)); }

.data-\[state\=selected\]\:bg-muted[data-state="selected"] { background-color: hsl(var(--muted)); }

.data-\[state\=unchecked\]\:bg-input[data-state="unchecked"] { background-color: hsl(var(--input)); }

.data-\[active\=true\]\:font-medium[data-active="true"] { font-weight: 500; }

.data-\[active\=true\]\:text-sidebar-accent-foreground[data-active="true"] { color: hsl(var(--sidebar-accent-foreground)); }

.data-\[selected\=true\]\:text-accent-foreground[data-selected="true"] { color: hsl(var(--accent-foreground)); }

.data-\[state\=active\]\:text-foreground[data-state="active"] { color: hsl(var(--foreground)); }

.data-\[state\=checked\]\:text-primary-foreground[data-state="checked"] { color: hsl(var(--primary-foreground)); }

.data-\[state\=on\]\:text-accent-foreground[data-state="on"], .data-\[state\=open\]\:text-accent-foreground[data-state="open"] { color: hsl(var(--accent-foreground)); }

.data-\[state\=open\]\:text-muted-foreground[data-state="open"] { color: hsl(var(--muted-foreground)); }

.data-\[disabled\=true\]\:opacity-50[data-disabled="true"], .data-\[disabled\]\:opacity-50[data-disabled] { opacity: 0.5; }

.data-\[state\=open\]\:opacity-100[data-state="open"] { opacity: 1; }

.data-\[state\=active\]\:shadow[data-state="active"] { --tw-shadow: 0 1px 3px 0 rgba(0,0,0,.1),0 1px 2px -1px rgba(0,0,0,.1); --tw-shadow-colored: 0 1px 3px 0 var(--tw-shadow-color),0 1px 2px -1px var(--tw-shadow-color); box-shadow: var(--tw-ring-offset-shadow,0 0 #0000),var(--tw-ring-shadow,0 0 #0000),var(--tw-shadow); }

.data-\[swipe\=move\]\:transition-none[data-swipe="move"] { transition-property: none; }

.data-\[state\=closed\]\:duration-300[data-state="closed"] { transition-duration: 0.3s; }

.data-\[state\=open\]\:duration-500[data-state="open"] { transition-duration: 0.5s; }

.data-\[motion\^\=from-\]\:animate-in[data-motion^="from-"], .data-\[state\=open\]\:animate-in[data-state="open"], .data-\[state\=visible\]\:animate-in[data-state="visible"] { animation-name: enter; animation-duration: 0.15s; --tw-enter-opacity: initial; --tw-enter-scale: initial; --tw-enter-rotate: initial; --tw-enter-translate-x: initial; --tw-enter-translate-y: initial; }

.data-\[motion\^\=to-\]\:animate-out[data-motion^="to-"], .data-\[state\=closed\]\:animate-out[data-state="closed"], .data-\[state\=hidden\]\:animate-out[data-state="hidden"], .data-\[swipe\=end\]\:animate-out[data-swipe="end"] { animation-name: exit; animation-duration: 0.15s; --tw-exit-opacity: initial; --tw-exit-scale: initial; --tw-exit-rotate: initial; --tw-exit-translate-x: initial; --tw-exit-translate-y: initial; }

.data-\[motion\^\=from-\]\:fade-in[data-motion^="from-"] { --tw-enter-opacity: 0; }

.data-\[motion\^\=to-\]\:fade-out[data-motion^="to-"], .data-\[state\=closed\]\:fade-out-0[data-state="closed"] { --tw-exit-opacity: 0; }

.data-\[state\=closed\]\:fade-out-80[data-state="closed"] { --tw-exit-opacity: 0.8; }

.data-\[state\=hidden\]\:fade-out[data-state="hidden"] { --tw-exit-opacity: 0; }

.data-\[state\=open\]\:fade-in-0[data-state="open"], .data-\[state\=visible\]\:fade-in[data-state="visible"] { --tw-enter-opacity: 0; }

.data-\[state\=closed\]\:zoom-out-95[data-state="closed"] { --tw-exit-scale: .95; }

.data-\[state\=open\]\:zoom-in-90[data-state="open"] { --tw-enter-scale: .9; }

.data-\[state\=open\]\:zoom-in-95[data-state="open"] { --tw-enter-scale: .95; }

.data-\[motion\=from-end\]\:slide-in-from-right-52[data-motion="from-end"] { --tw-enter-translate-x: 13rem; }

.data-\[motion\=from-start\]\:slide-in-from-left-52[data-motion="from-start"] { --tw-enter-translate-x: -13rem; }

.data-\[motion\=to-end\]\:slide-out-to-right-52[data-motion="to-end"] { --tw-exit-translate-x: 13rem; }

.data-\[motion\=to-start\]\:slide-out-to-left-52[data-motion="to-start"] { --tw-exit-translate-x: -13rem; }

.data-\[side\=bottom\]\:slide-in-from-top-2[data-side="bottom"] { --tw-enter-translate-y: -0.5rem; }

.data-\[side\=left\]\:slide-in-from-right-2[data-side="left"] { --tw-enter-translate-x: 0.5rem; }

.data-\[side\=right\]\:slide-in-from-left-2[data-side="right"] { --tw-enter-translate-x: -0.5rem; }

.data-\[side\=top\]\:slide-in-from-bottom-2[data-side="top"] { --tw-enter-translate-y: 0.5rem; }

.data-\[state\=closed\]\:slide-out-to-bottom[data-state="closed"] { --tw-exit-translate-y: 100%; }

.data-\[state\=closed\]\:slide-out-to-left[data-state="closed"] { --tw-exit-translate-x: -100%; }

.data-\[state\=closed\]\:slide-out-to-left-1\/2[data-state="closed"] { --tw-exit-translate-x: -50%; }

.data-\[state\=closed\]\:slide-out-to-right-full[data-state="closed"], .data-\[state\=closed\]\:slide-out-to-right[data-state="closed"] { --tw-exit-translate-x: 100%; }

.data-\[state\=closed\]\:slide-out-to-top[data-state="closed"] { --tw-exit-translate-y: -100%; }

.data-\[state\=closed\]\:slide-out-to-top-\[48\%\][data-state="closed"] { --tw-exit-translate-y: -48%; }

.data-\[state\=open\]\:slide-in-from-bottom[data-state="open"] { --tw-enter-translate-y: 100%; }

.data-\[state\=open\]\:slide-in-from-left[data-state="open"] { --tw-enter-translate-x: -100%; }

.data-\[state\=open\]\:slide-in-from-left-1\/2[data-state="open"] { --tw-enter-translate-x: -50%; }

.data-\[state\=open\]\:slide-in-from-right[data-state="open"] { --tw-enter-translate-x: 100%; }

.data-\[state\=open\]\:slide-in-from-top[data-state="open"] { --tw-enter-translate-y: -100%; }

.data-\[state\=open\]\:slide-in-from-top-\[48\%\][data-state="open"] { --tw-enter-translate-y: -48%; }

.data-\[state\=open\]\:slide-in-from-top-full[data-state="open"] { --tw-enter-translate-y: -100%; }

.data-\[state\=closed\]\:duration-300[data-state="closed"] { animation-duration: 0.3s; }

.data-\[state\=open\]\:duration-500[data-state="open"] { animation-duration: 0.5s; }

.data-\[panel-group-direction\=vertical\]\:after\:left-0[data-panel-group-direction="vertical"]::after { content: var(--tw-content); left: 0px; }

.data-\[panel-group-direction\=vertical\]\:after\:h-1[data-panel-group-direction="vertical"]::after { content: var(--tw-content); height: 0.25rem; }

.data-\[panel-group-direction\=vertical\]\:after\:w-full[data-panel-group-direction="vertical"]::after { content: var(--tw-content); width: 100%; }

.data-\[panel-group-direction\=vertical\]\:after\:-translate-y-1\/2[data-panel-group-direction="vertical"]::after { content: var(--tw-content); --tw-translate-y: -50%; transform: translate(var(--tw-translate-x),var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y)); }

.data-\[panel-group-direction\=vertical\]\:after\:translate-x-0[data-panel-group-direction="vertical"]::after { content: var(--tw-content); --tw-translate-x: 0px; transform: translate(var(--tw-translate-x),var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y)); }

.data-\[state\=open\]\:hover\:bg-sidebar-accent:hover[data-state="open"] { background-color: hsl(var(--sidebar-accent)); }

.data-\[state\=open\]\:hover\:text-sidebar-accent-foreground:hover[data-state="open"] { color: hsl(var(--sidebar-accent-foreground)); }

.group[data-collapsible="offcanvas"] .group-data-\[collapsible\=offcanvas\]\:left-\[calc\(var\(--sidebar-width\)\*-1\)\] { left: calc(var(--sidebar-width) * -1); }

.group[data-collapsible="offcanvas"] .group-data-\[collapsible\=offcanvas\]\:right-\[calc\(var\(--sidebar-width\)\*-1\)\] { right: calc(var(--sidebar-width) * -1); }

.group[data-side="left"] .group-data-\[side\=left\]\:-right-4 { right: -1rem; }

.group[data-side="right"] .group-data-\[side\=right\]\:left-0 { left: 0px; }

.group[data-collapsible="icon"] .group-data-\[collapsible\=icon\]\:-mt-8 { margin-top: -2rem; }

.group[data-collapsible="icon"] .group-data-\[collapsible\=icon\]\:hidden { display: none; }

.group[data-collapsible="icon"] .group-data-\[collapsible\=icon\]\:\!size-8 { width: 2rem !important; height: 2rem !important; }

.group[data-collapsible="icon"] .group-data-\[collapsible\=icon\]\:w-\[--sidebar-width-icon\] { width: var(--sidebar-width-icon); }

.group[data-collapsible="icon"] .group-data-\[collapsible\=icon\]\:w-\[calc\(var\(--sidebar-width-icon\)_\+_theme\(spacing\.4\)\)\] { width: calc(var(--sidebar-width-icon) + 1rem); }

.group[data-collapsible="icon"] .group-data-\[collapsible\=icon\]\:w-\[calc\(var\(--sidebar-width-icon\)_\+_theme\(spacing\.4\)_\+2px\)\] { width: calc(var(--sidebar-width-icon) + 1rem + 2px); }

.group[data-collapsible="offcanvas"] .group-data-\[collapsible\=offcanvas\]\:w-0 { width: 0px; }

.group[data-collapsible="offcanvas"] .group-data-\[collapsible\=offcanvas\]\:translate-x-0 { --tw-translate-x: 0px; transform: translate(var(--tw-translate-x),var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y)); }

.group[data-side="right"] .group-data-\[side\=right\]\:rotate-180, .group[data-state="open"] .group-data-\[state\=open\]\:rotate-180 { --tw-rotate: 180deg; transform: translate(var(--tw-translate-x),var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y)); }

.group[data-collapsible="icon"] .group-data-\[collapsible\=icon\]\:overflow-hidden { overflow: hidden; }

.group[data-variant="floating"] .group-data-\[variant\=floating\]\:rounded-lg { border-radius: var(--radius); }

.group[data-variant="floating"] .group-data-\[variant\=floating\]\:border { border-width: 1px; }

.group[data-side="left"] .group-data-\[side\=left\]\:border-r { border-right-width: 1px; }

.group[data-side="right"] .group-data-\[side\=right\]\:border-l { border-left-width: 1px; }

.group[data-variant="floating"] .group-data-\[variant\=floating\]\:border-sidebar-border { border-color: hsl(var(--sidebar-border)); }

.group[data-collapsible="icon"] .group-data-\[collapsible\=icon\]\:\!p-0 { padding: 0px !important; }

.group[data-collapsible="icon"] .group-data-\[collapsible\=icon\]\:\!p-2 { padding: 0.5rem !important; }

.group[data-collapsible="icon"] .group-data-\[collapsible\=icon\]\:opacity-0 { opacity: 0; }

.group[data-variant="floating"] .group-data-\[variant\=floating\]\:shadow { --tw-shadow: 0 1px 3px 0 rgba(0,0,0,.1),0 1px 2px -1px rgba(0,0,0,.1); --tw-shadow-colored: 0 1px 3px 0 var(--tw-shadow-color),0 1px 2px -1px var(--tw-shadow-color); box-shadow: var(--tw-ring-offset-shadow,0 0 #0000),var(--tw-ring-shadow,0 0 #0000),var(--tw-shadow); }

.group[data-collapsible="offcanvas"] .group-data-\[collapsible\=offcanvas\]\:after\:left-full::after { content: var(--tw-content); left: 100%; }

.group[data-collapsible="offcanvas"] .group-data-\[collapsible\=offcanvas\]\:hover\:bg-sidebar:hover { background-color: hsl(var(--sidebar-background)); }

.peer\/menu-button[data-size="default"] ~ .peer-data-\[size\=default\]\/menu-button\:top-1\.5 { top: 0.375rem; }

.peer\/menu-button[data-size="lg"] ~ .peer-data-\[size\=lg\]\/menu-button\:top-2\.5 { top: 0.625rem; }

.peer\/menu-button[data-size="sm"] ~ .peer-data-\[size\=sm\]\/menu-button\:top-1 { top: 0.25rem; }

.peer[data-variant="inset"] ~ .peer-data-\[variant\=inset\]\:min-h-\[calc\(100svh-theme\(spacing\.4\)\)\] { min-height: calc(-1rem + 100svh); }

.peer\/menu-button[data-active="true"] ~ .peer-data-\[active\=true\]\/menu-button\:text-sidebar-accent-foreground { color: hsl(var(--sidebar-accent-foreground)); }

.dark\:border-destructive:is(.dark *) { border-color: hsl(var(--destructive)); }

@media (min-width: 640px) {
  .sm\:bottom-0 { bottom: 0px; }
  .sm\:right-0 { right: 0px; }
  .sm\:top-auto { top: auto; }
  .sm\:mt-0 { margin-top: 0px; }
  .sm\:flex { display: flex; }
  .sm\:max-w-sm { max-width: 24rem; }
  .sm\:flex-row { flex-direction: row; }
  .sm\:flex-col { flex-direction: column; }
  .sm\:justify-end { justify-content: flex-end; }
  .sm\:gap-2\.5 { gap: 0.625rem; }
  .sm\:space-x-2 > :not([hidden]) ~ :not([hidden]) { --tw-space-x-reverse: 0; margin-right: calc(.5rem * var(--tw-space-x-reverse)); margin-left: calc(.5rem * calc(1 - var(--tw-space-x-reverse))); }
  .sm\:space-x-4 > :not([hidden]) ~ :not([hidden]) { --tw-space-x-reverse: 0; margin-right: calc(1rem * var(--tw-space-x-reverse)); margin-left: calc(1rem * calc(1 - var(--tw-space-x-reverse))); }
  .sm\:space-y-0 > :not([hidden]) ~ :not([hidden]) { --tw-space-y-reverse: 0; margin-top: calc(0px * calc(1 - var(--tw-space-y-reverse))); margin-bottom: calc(0px * var(--tw-space-y-reverse)); }
  .sm\:rounded-lg { border-radius: var(--radius); }
  .sm\:text-left { text-align: left; }
  .data-\[state\=open\]\:sm\:slide-in-from-bottom-full[data-state="open"] { --tw-enter-translate-y: 100%; }
}

@media (min-width: 768px) {
  .md\:absolute { position: absolute; }
  .md\:block { display: block; }
  .md\:flex { display: flex; }
  .md\:w-64 { width: 16rem; }
  .md\:w-\[var\(--radix-navigation-menu-viewport-width\)\] { width: var(--radix-navigation-menu-viewport-width); }
  .md\:w-auto { width: auto; }
  .md\:max-w-\[420px\] { max-width: 420px; }
  .md\:flex-row { flex-direction: row; }
  .md\:text-sm { font-size: 0.875rem; line-height: 1.25rem; }
  .md\:opacity-0 { opacity: 0; }
  .after\:md\:hidden::after { content: var(--tw-content); display: none; }
  .peer[data-variant="inset"] ~ .md\:peer-data-\[variant\=inset\]\:m-2 { margin: 0.5rem; }
  .peer[data-state="collapsed"][data-variant="inset"] ~ .md\:peer-data-\[state\=collapsed\]\:peer-data-\[variant\=inset\]\:ml-2 { margin-left: 0.5rem; }
  .peer[data-variant="inset"] ~ .md\:peer-data-\[variant\=inset\]\:ml-0 { margin-left: 0px; }
  .peer[data-variant="inset"] ~ .md\:peer-data-\[variant\=inset\]\:rounded-xl { border-radius: 0.75rem; }
  .peer[data-variant="inset"] ~ .md\:peer-data-\[variant\=inset\]\:shadow { --tw-shadow: 0 1px 3px 0 rgba(0,0,0,.1),0 1px 2px -1px rgba(0,0,0,.1); --tw-shadow-colored: 0 1px 3px 0 var(--tw-shadow-color),0 1px 2px -1px var(--tw-shadow-color); box-shadow: var(--tw-ring-offset-shadow,0 0 #0000),var(--tw-ring-shadow,0 0 #0000),var(--tw-shadow); }
}

.\[\&\+div\]\:text-xs + div { font-size: 0.75rem; line-height: 1rem; }

.\[\&\:has\(\>\.day-range-end\)\]\:rounded-r-md:has(> .day-range-end) { border-top-right-radius: calc(var(--radius) - 2px); border-bottom-right-radius: calc(var(--radius) - 2px); }

.\[\&\:has\(\>\.day-range-start\)\]\:rounded-l-md:has(> .day-range-start) { border-top-left-radius: calc(var(--radius) - 2px); border-bottom-left-radius: calc(var(--radius) - 2px); }

.\[\&\:has\(\[aria-selected\]\)\]\:rounded-md:has([aria-selected]) { border-radius: calc(var(--radius) - 2px); }

.\[\&\:has\(\[aria-selected\]\)\]\:bg-accent:has([aria-selected]) { background-color: hsl(var(--accent)); }

.first\:\[\&\:has\(\[aria-selected\]\)\]\:rounded-l-md:has([aria-selected]):first-child { border-top-left-radius: calc(var(--radius) - 2px); border-bottom-left-radius: calc(var(--radius) - 2px); }

.last\:\[\&\:has\(\[aria-selected\]\)\]\:rounded-r-md:has([aria-selected]):last-child { border-top-right-radius: calc(var(--radius) - 2px); border-bottom-right-radius: calc(var(--radius) - 2px); }

.\[\&\:has\(\[aria-selected\]\.day-outside\)\]\:bg-accent\/50:has([aria-selected].day-outside) { background-color: hsl(var(--accent)/.5); }

.\[\&\:has\(\[aria-selected\]\.day-range-end\)\]\:rounded-r-md:has([aria-selected].day-range-end) { border-top-right-radius: calc(var(--radius) - 2px); border-bottom-right-radius: calc(var(--radius) - 2px); }

.\[\&\:has\(\[role\=checkbox\]\)\]\:pr-0:has([role="checkbox"]) { padding-right: 0px; }

.\[\&\>\[role\=checkbox\]\]\:translate-y-\[2px\] > [role="checkbox"] { --tw-translate-y: 2px; transform: translate(var(--tw-translate-x),var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y)); }

.\[\&\>button\]\:hidden > button { display: none; }

.\[\&\>span\:last-child\]\:truncate > span:last-child { overflow: hidden; text-overflow: ellipsis; white-space: nowrap; }

.\[\&\>span\]\:line-clamp-1 > span { overflow: hidden; display: -webkit-box; -webkit-box-orient: vertical; -webkit-line-clamp: 1; }

.\[\&\>svg\+div\]\:translate-y-\[-3px\] > svg + div { --tw-translate-y: -3px; transform: translate(var(--tw-translate-x),var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y)); }

.\[\&\>svg\]\:absolute > svg { position: absolute; }

.\[\&\>svg\]\:left-4 > svg { left: 1rem; }

.\[\&\>svg\]\:top-4 > svg { top: 1rem; }

.\[\&\>svg\]\:size-4 > svg { width: 1rem; height: 1rem; }

.\[\&\>svg\]\:h-2\.5 > svg { height: 0.625rem; }

.\[\&\>svg\]\:h-3 > svg { height: 0.75rem; }

.\[\&\>svg\]\:h-3\.5 > svg { height: 0.875rem; }

.\[\&\>svg\]\:w-2\.5 > svg { width: 0.625rem; }

.\[\&\>svg\]\:w-3 > svg { width: 0.75rem; }

.\[\&\>svg\]\:w-3\.5 > svg { width: 0.875rem; }

.\[\&\>svg\]\:shrink-0 > svg { flex-shrink: 0; }

.\[\&\>svg\]\:text-destructive > svg { color: hsl(var(--destructive)); }

.\[\&\>svg\]\:text-foreground > svg { color: hsl(var(--foreground)); }

.\[\&\>svg\]\:text-muted-foreground > svg { color: hsl(var(--muted-foreground)); }

.\[\&\>svg\]\:text-sidebar-accent-foreground > svg { color: hsl(var(--sidebar-accent-foreground)); }

.\[\&\>svg\~\*\]\:pl-7 > svg ~ * { padding-left: 1.75rem; }

.\[\&\>tr\]\:last\:border-b-0:last-child > tr { border-bottom-width: 0px; }

.\[\&\[data-panel-group-direction\=vertical\]\>div\]\:rotate-90[data-panel-group-direction="vertical"] > div { --tw-rotate: 90deg; }

.\[\&\[data-panel-group-direction\=vertical\]\>div\]\:rotate-90[data-panel-group-direction="vertical"] > div, .\[\&\[data-state\=open\]\>svg\]\:rotate-180[data-state="open"] > svg { transform: translate(var(--tw-translate-x),var(--tw-translate-y)) rotate(var(--tw-rotate)) skewX(var(--tw-skew-x)) skewY(var(--tw-skew-y)) scaleX(var(--tw-scale-x)) scaleY(var(--tw-scale-y)); }

.\[\&\[data-state\=open\]\>svg\]\:rotate-180[data-state="open"] > svg { --tw-rotate: 180deg; }

.\[\&_\.recharts-cartesian-axis-tick_text\]\:fill-muted-foreground .recharts-cartesian-axis-tick text { fill: hsl(var(--muted-foreground)); }

.\[\&_\.recharts-cartesian-grid_line\[stroke\=\'\#ccc\'\]\]\:stroke-border\/50 .recharts-cartesian-grid line[stroke="#ccc"] { stroke: hsl(var(--border)/.5); }

.\[\&_\.recharts-curve\.recharts-tooltip-cursor\]\:stroke-border .recharts-curve.recharts-tooltip-cursor { stroke: hsl(var(--border)); }

.\[\&_\.recharts-dot\[stroke\=\'\#fff\'\]\]\:stroke-transparent .recharts-dot[stroke="#fff"] { stroke: transparent; }

.\[\&_\.recharts-layer\]\:outline-none .recharts-layer { outline: transparent solid 2px; outline-offset: 2px; }

.\[\&_\.recharts-polar-grid_\[stroke\=\'\#ccc\'\]\]\:stroke-border .recharts-polar-grid [stroke="#ccc"] { stroke: hsl(var(--border)); }

.\[\&_\.recharts-radial-bar-background-sector\]\:fill-muted .recharts-radial-bar-background-sector, .\[\&_\.recharts-rectangle\.recharts-tooltip-cursor\]\:fill-muted .recharts-rectangle.recharts-tooltip-cursor { fill: hsl(var(--muted)); }

.\[\&_\.recharts-reference-line_\[stroke\=\'\#ccc\'\]\]\:stroke-border .recharts-reference-line [stroke="#ccc"] { stroke: hsl(var(--border)); }

.\[\&_\.recharts-sector\[stroke\=\'\#fff\'\]\]\:stroke-transparent .recharts-sector[stroke="#fff"] { stroke: transparent; }

.\[\&_\.recharts-sector\]\:outline-none .recharts-sector, .\[\&_\.recharts-surface\]\:outline-none .recharts-surface { outline: transparent solid 2px; outline-offset: 2px; }

.\[\&_\[cmdk-group-heading\]\]\:px-2 [cmdk-group-heading] { padding-left: 0.5rem; padding-right: 0.5rem; }

.\[\&_\[cmdk-group-heading\]\]\:py-1\.5 [cmdk-group-heading] { padding-top: 0.375rem; padding-bottom: 0.375rem; }

.\[\&_\[cmdk-group-heading\]\]\:text-xs [cmdk-group-heading] { font-size: 0.75rem; line-height: 1rem; }

.\[\&_\[cmdk-group-heading\]\]\:font-medium [cmdk-group-heading] { font-weight: 500; }

.\[\&_\[cmdk-group-heading\]\]\:text-muted-foreground [cmdk-group-heading] { color: hsl(var(--muted-foreground)); }

.\[\&_\[cmdk-group\]\:not\(\[hidden\]\)_\~\[cmdk-group\]\]\:pt-0 [cmdk-group]:not([hidden]) ~ [cmdk-group] { padding-top: 0px; }

.\[\&_\[cmdk-group\]\]\:px-2 [cmdk-group] { padding-left: 0.5rem; padding-right: 0.5rem; }

.\[\&_\[cmdk-input-wrapper\]_svg\]\:h-5 [cmdk-input-wrapper] svg { height: 1.25rem; }

.\[\&_\[cmdk-input-wrapper\]_svg\]\:w-5 [cmdk-input-wrapper] svg { width: 1.25rem; }

.\[\&_\[cmdk-input\]\]\:h-12 [cmdk-input] { height: 3rem; }

.\[\&_\[cmdk-item\]\]\:px-2 [cmdk-item] { padding-left: 0.5rem; padding-right: 0.5rem; }

.\[\&_\[cmdk-item\]\]\:py-3 [cmdk-item] { padding-top: 0.75rem; padding-bottom: 0.75rem; }

.\[\&_\[cmdk-item\]_svg\]\:h-5 [cmdk-item] svg { height: 1.25rem; }

.\[\&_\[cmdk-item\]_svg\]\:w-5 [cmdk-item] svg { width: 1.25rem; }

.\[\&_p\]\:leading-relaxed p { line-height: 1.625; }

.\[\&_svg\]\:pointer-events-none svg { pointer-events: none; }

.\[\&_svg\]\:size-4 svg { width: 1rem; height: 1rem; }

.\[\&_svg\]\:shrink-0 svg { flex-shrink: 0; }

.\[\&_tr\:last-child\]\:border-0 tr:last-child { border-width: 0px; }

.\[\&_tr\]\:border-b tr { border-bottom-width: 1px; }

[data-side="left"][data-collapsible="offcanvas"] .\[\[data-side\=left\]\[data-collapsible\=offcanvas\]_\&\]\:-right-2 { right: -0.5rem; }

[data-side="left"][data-state="collapsed"] .\[\[data-side\=left\]\[data-state\=collapsed\]_\&\]\:cursor-e-resize { cursor: e-resize; }

[data-side="left"] .\[\[data-side\=left\]_\&\]\:cursor-w-resize { cursor: w-resize; }

[data-side="right"][data-collapsible="offcanvas"] .\[\[data-side\=right\]\[data-collapsible\=offcanvas\]_\&\]\:-left-2 { left: -0.5rem; }

[data-side="right"][data-state="collapsed"] .\[\[data-side\=right\]\[data-state\=collapsed\]_\&\]\:cursor-w-resize { cursor: w-resize; }

[data-side="right"] .\[\[data-side\=right\]_\&\]\:cursor-e-resize { cursor: e-resize; }
------MultipartBoundary--0qBUgy5tPqKL35ZdjCbOOhQnRB2eG5WhwTDH1o7iZA------
